Updated `from_dir` to check parent directories
FuelLabs/sway pull request #1232
Opened 2022-04-12 23:28 UTC by eureka-cpu

Adds `find_manifest_dir` function to `manifest::from_dir` method since we commonly check that a parent directory contains a `Forc.toml`. I've also moved `check_project_type` function as a method on `Manifest` as well since its use case was associated with `Manifest` and may later be moved into a `from_dir_expecting_program_type` method.

Tracking: #1107

2022-04-13 00:08 UTC, eureka-cpu commented
@mitchmindtree previously you asked to add a check for the parent directories to `manifest::from_dir` and also have it check the `tree_type`. I've sort of organized things to set that up and just want to make sure you still want `from_dir` to handle all of that.

2022-04-13 00:45 UTC, eureka-cpu commented
`reentrancy` & `tx_fields` tests in `lib-std` don't have a `Forc.toml` which is why it's currently failing

2022-04-13 03:07 UTC, mitchmindtree requested changes
Most of these comments are related to the same issue: passing around the manifest directory path.

Generally whenever we use the `Manifest` for something useful (getting the entry point string, checking the program type) we also require knowing the manifest directory.

The idea of having the manifest store the path has been on my mind for a while as a solution to this, but I don't think the `Manifest` type itself is a good place for it. The `Manifest` should remain a pure, TOML-serializable reflection of the `Forc.toml` structure, in particular to support cases where the manifest is loaded from an in-memory `&str` and not a file. This is likely only going to be the case for tests, but I still think it would be good practice to avoid storing a redundant path even in those cases.

Instead, I think we should add something like the following to the `manifest` module:

```rust
pub struct ManifestFile {
    /// The deserialized `Forc.toml`.
    manifest: Manifest,
    /// The path from which the `Forc.toml` file was read.
    path: PathBuf,
}
```

Then, each of the `Manifest` constructors and methods that refer to a path or directory in any way should be moved to this `ManifestFile` type. Similarly, we should use this new type anywhere in `forc` where we read the manifest from a file.


The `ManifestFile` type should also expose methods like:

```rust
/// The path to the `Forc.toml` from which this manifest was loaded. 
pub fn path(&self) -> &Path {
    &self.path
}

/// The path to the directory containing the `Forc.toml` from which this manfiest was loaded.
pub fn dir(&self) -> &Path {
    self.path().parent().expect("failed to retrieve manifest directory")
}
```

These methods could be used rather than having to pass the manifest directory everywhere we pass the manifest.

What are your thoughts?

2022-04-13 03:59 UTC, eureka-cpu commented on forc/src/ops/forc_abi_json.rs
> +        .check_program_type(curr_dir, TreeType::Contract)?;
Ah, I see! Would it make sense then to move `check_program_type` into `from_dir` then, so that it can access `manifest_dir`?

2022-04-13 04:03 UTC, eureka-cpu commented
>What are your thoughts?

I like this idea of further separating so that the path is managed separately, but this PR is just to remove code bloat. I'll file an issue and tag it here, and fix up the previous mistakes I had made regarding the directory I was giving to the functions.

2022-04-13 18:40 UTC, eureka-cpu commented on forc/src/ops/forc_abi_json.rs
> +        .check_program_type(curr_dir, TreeType::Contract)?;
Opened #1242 to track your above comment

2022-04-14 13:20 UTC, mitchmindtree approved these changes

2022-04-14 13:21 UTC, merged