Updated `forc-init` with `--contract`, `--script`, etc.
FuelLabs/sway pull request #1351
Opened 2022-04-21 17:47 UTC by eureka-cpu

Closes #1186 

Currently WIP: Adds a `project_type` to the `InitCommand` struct which is an `Option<String>`, checks for `Some` or `None` and if `None` then it will default to `contract`. Also added some wip default programs to `defaults`.

2022-04-21 18:01 UTC, sezna commented on forc/src/ops/forc_init.rs
> +    let project_type = match command.project_type {
[structopt has an option for a default value](https://docs.rs/structopt/latest/structopt/#how-to-derivestructopt).

You can [also make the lowercasing part of structopt as well](https://docs.rs/structopt/latest/structopt/#custom-string-parsers)

2022-04-21 20:41 UTC, eureka-cpu commented
@adlerjohn currently this command would look like: `forc init <project_name> <project_type>` and wouldn't need the `--`. Personally I think this is cleaner for internal use, and for anyone creating a `contract` you could leave out the `project_type` bit. We could also make it a flag, and this would look like `... --project-type <project_type>`.

2022-04-21 21:46 UTC, Braqzen commented
How about the order is changed to have the project name be at the end?
E.g. `forc init <project name>` defaults to a contract and for a different program type the program type would be put before the project name but after the init i.e. `forc init <program type> <project name>`.

2022-04-21 22:25 UTC, eureka-cpu commented
> How about the order is changed to have the project name be at the end? E.g. `forc init <project name>` defaults to a contract and for a different program type the program type would be put before the project name but after the init i.e. `forc init <program type> <project name>`.

This was the initially approach, but unfortunately `clap` has trouble determining which is the name of the project and which is the project type. cc @sezna for a more detailed explanation than I could give.

2022-04-21 22:31 UTC, adlerjohn commented
Since program type is optional, it should be at the end.

2022-04-21 22:48 UTC, eureka-cpu commented
> Since program type is optional, it should be at the end.

Should it be an Option, or an Arg?

2022-04-22 03:48 UTC, mitchmindtree commented
Perhaps it might be nicer to match `cargo new` behaviour here?

Some examples:

- `cargo new --lib my-lib` - creates a library called `my-lib`
- `cargo new --bin my-app` - creates a binary called `my-app`
- `cargo new my-app` - default behaviour creates a binary called `my-app`

When discussing support init with program types, I was imagine we'd have something similar for forc. For example:

- `forc init --contract my-contract`
- `forc init --library my-lib`
- `forc init --script my-script`
- `forc init --predicate my-pred`
- `forc init my-contract`

Perhaps this is a little more concise / approachable?

I think we could achieve this behaviour by adding these flags as `bool`s to the `InitCommand`, but I could be wrong. Then we can do something like:

```rust
let prog_type = match (cmd.contract, cmd.library, cmd.script, cmd.predicate) {
    (false, true, false, false) => /* library */,
    (false, false, true, false) => /* script */,
    (false, false, false, true) => /* predicate */,
    (_, false, false, false) => /* contract */,
    _ => /* return err: can only pick one program type */,
};
```

### project type -> program type

Much of the terminology in this PR and discussion has been around "project-type", however in the Sway book I believe we use the term "**program** type". I'd be open to seeing the terminology used in the book bike-shedded/discussed, but in this PR we should probably be consistent and follow the terminology that currently exists in the book.

2022-04-22 07:03 UTC, adlerjohn commented
My personal preference is to always imitate Rust and Cargo unless there's an explicit reason not to.

2022-04-22 21:42 UTC, adlerjohn commented on forc/src/ops/forc_init.rs
> +        \n Possible Types:\n - contract\n - script\n - predicate\n - library"
?
```suggestion
        \n Possible Types:\n - contract\n - script\n - predicate\n - lib"
```

2022-04-22 21:59 UTC, adlerjohn reviewed
Looks fine to me but I'll defer to others.

2022-04-24 02:05 UTC, mitchmindtree requested changes
Great stuff! One last nit, otherwise utACK :+1:

2022-04-24 02:05 UTC, mitchmindtree commented on forc/src/ops/forc_init.rs
> +    // Insert project based on project_type
```suggestion
    // Insert src based on program_type
```

2022-04-25 23:38 UTC, mitchmindtree commented on forc/src/cli/commands/init.rs
> +    #[clap(long = "lib")]
It feels a little odd only having a short-hand name for the `library` type but not for the others. Maybe we can omit this shorthand for now and discuss whether or not we want short-hands in another issue?

2022-04-25 23:38 UTC, mitchmindtree commented on forc/src/ops/forc_init.rs
> +        \n Possible Types:\n - contract\n - script\n - predicate\n - lib"
If we remove the shorthand for library, we should update this msg too.

2022-04-26 00:05 UTC, mitchmindtree approved these changes

2022-04-26 00:19 UTC, merged