Add build-forc-test-project to ci
FuelLabs/sway pull request #1409
Opened 2022-04-27 00:58 UTC by ra0x3

2022-04-27 01:08 UTC, mohammadfawaz commented on .github/workflows/ci.yml
> -        run: furc test --path test-proj
Ok, `furc test` sounds awesome.

2022-04-27 03:51 UTC, mitchmindtree requested changes

2022-04-27 03:51 UTC, mitchmindtree commented on .github/workflows/ci.yml
> +  build-forc-test-project:
Could you add this new job to the list of `needs` for each of the publish jobs?

2022-04-29 03:26 UTC, mitchmindtree requested changes

2022-04-29 03:26 UTC, mitchmindtree commented on .github/workflows/ci.yml
> +        build-forc-test-project,
Could you also add this to the `needs` arrays for the `notify-slack-on-failure` and `publish` jobs?

2022-05-01 03:01 UTC, mitchmindtree commented on .github/workflows/ci.yml
> +        build-forc-test-project,
@ra0x3 we're still missing this under the `publish` job.

2022-05-02 00:33 UTC, mitchmindtree approved these changes
Nice, I think this should make for a good start!

Currently this only tests the default init type (`--contract`) but we can extend this with each of the different init types (i.e. `--contract`, `--library`, `--predicate`, `--script`) in a follow-up PR. This could be a good use-case for the CI matrix feature, e.g. https://github.com/FuelLabs/fuel-core/commit/344115aa6c6a18863496cdf2dc6bb6e3fba05e94#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR57

2022-05-02 15:01 UTC, merged

2022-05-02 16:16 UTC, ra0x3 commented
> Nice, I think this should make for a good start!

@mitchmindtree 
- I agree we should add the other implementation as well eventually. I can create this as a `goodfirstissue` 
- I see that Github actions allows for parallel jobs via the `matrix` - we should definitely parallelize what we can to speed up CI (not super hugely important however)
- My question here is -- I see many of our CI jobs that seem to be independent of other jobs (this job I just merged for example). Is there any reason we're not using a `matrix` strategy on these jobs currently?