Add [workspace] to forc manifest
FuelLabs/sway pull request #1461
Opened 2022-05-03 15:15 UTC by ra0x3

### Description
- This PR adds a `[manifest]` to the `build-forc-test-project` job's cargo manifest

### Testing Steps
- [ ] CI should pass and `build-forc-test-project` specifically should have no errors during any steps

2022-05-03 16:23 UTC, adlerjohn requested changes
CI is actually failing on [89f2ff1](https://github.com/FuelLabs/sway/pull/1461/commits/89f2ff1979ee4bbf0f381470e6271a603dedb4ba): https://github.com/FuelLabs/sway/runs/6276075112?check_suite_focus=true (see Run test project's test suite job).

```
error: failed to parse manifest at `/home/runner/work/sway/sway/test-proj/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  TOML parse error at line 20, column 1
     |
  20 | \n[workspace]
     | ^
  Could not parse the line
```

But `forc test` doesn't actually return an error code so it's not picked up by CI. This is a bug in `forc.

2022-05-03 16:25 UTC, ra0x3 commented
@adlerjohn Hey yea I see. Currently away, but I’ll address it when I get back 👌🏽

2022-05-03 20:23 UTC, adlerjohn commented
Filed #1464 to follow up on the above-noticed bug.

2022-05-03 20:23 UTC, adlerjohn approved these changes

2022-05-04 22:53 UTC, sezna approved these changes

2022-05-04 23:44 UTC, merged