Manifest files use env variable to set author or default back to the …
FuelLabs/sway pull request #1487
Opened 2022-05-05 15:10 UTC by Braqzen

…realname

Closes #1484

2022-05-05 15:16 UTC, adlerjohn commented on forc/src/utils/defaults.rs
> +    let author = match std::env::var("FORC_INIT_MANIFEST_AUTHOR") {
Abstract this string into a constant since it's used more than once and is part of the public API.

2022-05-05 15:35 UTC, adlerjohn commented on forc/src/utils/defaults.rs
> +    let author = match std::env::var("FORC_INIT_MANIFEST_AUTHOR") {
Fixed in [afe7cd6](https://github.com/FuelLabs/sway/pull/1487/commits/afe7cd62ff64983632cf2c9bf4b17be7074c47ad)

2022-05-05 15:35 UTC, adlerjohn submitted a review, later dismissed
Looks fine to me, but will defer to tooling team.

2022-05-06 03:34 UTC, eureka-cpu reviewed
If possible, since we're using the same code twice here, could you make a function possibly called `get_author` and call it for those variables? Just trying to tackle code bloat when I see it so we don't have to go back and fix it later, if this is a blocker it could also just be added to #1107 for a separate PR

2022-05-06 04:22 UTC, otrho submitted a review, later dismissed

2022-05-06 04:22 UTC, otrho commented on forc/src/utils/defaults.rs
> +    };
FYI a simpler way to do this pattern is:
```rust
let author =
    std::env::var(sway_utils::FORC_INIT_MANIFEST_AUTHOR).unwrap_or_else(|| whoami::realname());
```

2022-05-06 04:25 UTC, JoshuaBatty requested changes
Thanks @Braqzen! Can you please make the suggested edits that were made by @otrho and @eureka-cpu first before landing this?

2022-05-06 14:43 UTC, eureka-cpu approved these changes
looking clean, thanks!

2022-05-10 01:01 UTC, JoshuaBatty approved these changes

2022-05-10 01:02 UTC, JoshuaBatty commented
Looks good, thanks @Braqzen

2022-05-10 05:54 UTC, merged