Use `__` as a prefix for compiler intrinsics
FuelLabs/sway pull request #1536
Opened 2022-05-12 21:36 UTC by sezna

Closes #1531
Closes #1533

2022-05-12 22:59 UTC, adlerjohn reviewed
CI failing

2022-05-12 23:19 UTC, mohammadfawaz commented
I think you just forgot to update "should_pass/language/size_of"

2022-05-12 23:21 UTC, adlerjohn commented
> Yeah but your `size_of` is not `size_of`

2022-05-13 00:46 UTC, adlerjohn reviewed
fmt Sway files, and it looks like none of the added tests actually use `core`, so use `implicit_std = false` instead.

2022-05-13 01:51 UTC, otrho requested changes
Looks good otherwise.

2022-05-13 01:51 UTC, otrho commented on sway-parse/src/error.rs
> +    #[error("Expected an item")]
```suggestion
    #[error("Expected an item.")]
```

2022-05-13 01:51 UTC, otrho commented on sway-parse/src/item/mod.rs
> +        let name: Ident = parser.parse()?;
Why is this change needed all of a sudden?  Isn't the type implied on line 285?

2022-05-13 15:51 UTC, adlerjohn requested changes

2022-05-13 16:58 UTC, adlerjohn approved these changes

2022-05-13 17:29 UTC, mohammadfawaz approved these changes

2022-05-13 22:33 UTC, otrho approved these changes

2022-05-14 13:04 UTC, merged