Implement left & right shift for `b256`
FuelLabs/sway pull request #1549
Opened 2022-05-14 19:40 UTC by nfurfaro

2022-05-16 02:38 UTC, nfurfaro commented
Blocked, waiting for a fuel-vm release with these changes: https://github.com/FuelLabs/fuel-vm/pull/113

2022-05-16 02:46 UTC, nfurfaro commented on sway-lib-core/src/ops.sw
> +fn log_u64(val: u64) {
temp debugging func

2022-05-26 16:52 UTC, nfurfaro commented on sway-lib-core/src/ops.sw
> +        let(value_word_1, value_word_2, value_word_3, value_word_4) = decompose(val);
weird format thing, we'll see if CI complains. (this is forc formatter)

2022-05-26 16:53 UTC, nfurfaro commented on sway-lib-core/src/ops.sw
> +pub trait Shiftable {
moved Shiftable trait down so it can use other traits above. This is already tracked in an issue.

2022-05-26 17:39 UTC, adlerjohn requested changes

2022-05-26 17:39 UTC, adlerjohn commented on sway-lib-core/src/ops.sw
> +const FLAG = 2;
Unused, remove.

2022-05-26 17:39 UTC, adlerjohn commented on sway-lib-core/src/ops.sw
> +        out: (u64, u64) // return both values
Do this outside of asm. See: https://github.com/FuelLabs/sway/blob/609bcb42ccdba9d4a89aa1085e0fb3698ca2c41a/sway-lib-std/src/u128.sw#L195-L199

2022-05-26 18:06 UTC, adlerjohn approved these changes

2022-05-26 18:14 UTC, merged