Monomorphize method applications
FuelLabs/sway pull request #1671
Opened 2022-05-25 17:31 UTC by sezna

We were not monomorphizing method applications at all. This PR fixes that. This change was made much easier by #1589  and #1666 

Closes #1628 

This PR works by monomorphizing declarations when methods are instantiated against them.  This now means that you can annotate types for a parent type and a function, like Rust.

So, this example works:

```rust

struct Foo<T> {
  a: T
}
impl <T> Foo {
   fn bar<O>(o: O) -> u64 {
     5
  }
}
fn main() {
      // note the annotation `u64` for `Foo` and `bool` for `bar()`
    Foo::<u64>::bar::<bool>(true)
}

```

This involved changes to the parser to allow generic arguments in the new position and calling `monomorphize` on declarations when methods are instantiated. All the other changes are just fallout from those two things.

edit: some interaction with recent PRs has broken some tests, moving to draft while that gets sorted out...

2022-05-28 00:15 UTC, AlicanC reviewed
I tried this on my local while working on the Multicall script and it indeed solves my issues! Can do things a lot more conveniently now 👍 👍 👍 👍

2022-05-28 04:53 UTC, otrho requested changes
LGTM, though I'm not the type checker expert.

2022-05-28 04:53 UTC, otrho commented on sway-core/src/convert_parse_tree.rs
> +                                println!("here?1");
```suggestion
```

2022-05-28 14:19 UTC, emilyaherbert requested changes

2022-05-28 14:19 UTC, emilyaherbert commented on sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
> +    // monomorphize the parent type
remove

2022-05-28 14:19 UTC, emilyaherbert commented on sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
> +    let ty = (|| -> CompileResult<TypeId> {
Is it necessary to use a function closure here? This makes it harder to read and maintain IMO.

2022-05-28 14:19 UTC, emilyaherbert commented on test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self/src/main.sw
> +  ~DoubleIdentity::<T, F>::new(x, y)
Can you explain the reason for changing the syntax?

2022-06-07 00:55 UTC, emilyaherbert commented
Based on our convo @sezna, I'm going to close this PR, copy your parser changes to a new PR, then take over https://github.com/FuelLabs/sway/issues/1628.

2022-06-07 00:55 UTC, closed without merging