[LSP] Replace logging with tracing
FuelLabs/sway pull request #2925
Opened 2022-10-03 23:55 UTC by sdankel

Related https://github.com/FuelLabs/sway/issues/2286

2022-10-07 05:38 UTC, JoshuaBatty commented
Nice, this is going to be super handy to have! Looks like there are just a few clippy warnings that need addressing.

2022-10-21 05:26 UTC, JoshuaBatty requested changes
LGTM, thanks for this! Just one thing to be removed and I'll be happy to approve.

2022-10-21 05:26 UTC, JoshuaBatty commented on sway-lsp/src/lib.rs
> +        log_level: Some(LevelFilter::DEBUG), // TODO: Set this based on IDE config
sounds good, we can have a chat next week and I can talk you though how to go about setting something like this up.

2022-10-21 05:26 UTC, JoshuaBatty commented on sway-lsp/src/server.rs
> +        tracing::error!("InitializeParams = {:#?}", params);
The existing `eprintln!("InitializeParams = {:#?}", params);` was accidentally left over from a previous PR. Can we remove this line?

2022-10-23 22:28 UTC, JoshuaBatty submitted a review, later dismissed

2022-10-24 05:11 UTC, mitchmindtree approved these changes

2022-10-24 05:20 UTC, otrho approved these changes

2022-10-24 05:29 UTC, JoshuaBatty approved these changes

2022-10-24 05:34 UTC, merged