Introduce code relocation to avoid the need for far jumps.
FuelLabs/sway pull request #3371
Opened 2022-11-15 19:56 UTC by otrho

The existing solution for far jumps which can't fit in an immediate is to convert them to dynamic jumps, storing the destination address in the data section.

This change helps avoid far jumps altogether by moving large blocks to beyond the limit to keep immediate mode control flow.

Closes #3347

2022-11-21 20:21 UTC, mohammadfawaz submitted a review, later dismissed

2022-11-22 00:15 UTC, emilyaherbert requested changes
> It doesn't strictly fix the https://github.com/FuelLabs/sway/issues/3161 problem but it makes it very much less likely to occur.

Can you help me get an intuition for what the circumstances would be in which this issue would occur still?

Just a few questions on my end, otherwise---awesome work!

2022-11-22 00:15 UTC, emilyaherbert commented on sway-core/src/asm_generation/allocated_abstract_instruction_set.rs
> +        // Do an analysis pass, gathering basic block offsets and whether any jumps are going to be
Can you describe what it would mean for a jump to be a problem?

2022-11-22 00:15 UTC, emilyaherbert commented on sway-core/src/asm_generation/allocated_abstract_instruction_set.rs
> +        // Do an analysis pass, gathering basic block offsets and whether any jumps are going to be
(Document this in the code I mean)

2022-11-24 02:40 UTC, mohammadfawaz commented on sway-core/src/asm_generation/allocated_abstract_instruction_set.rs
> +    /// Relocate code to keep as much control flow below the magic 1MB address space accessible by
Toby clarified this in his latest commit. Basically it's just the size of the bytecode that can be addressed using the 18-bit immediate of `jnzi`.

2022-11-29 02:38 UTC, merged