Remove the global `DeclarationEngine`
FuelLabs/sway pull request #3411
Opened 2022-11-22 18:30 UTC by emilyaherbert

Closes #2063

2022-12-17 02:07 UTC, JoshuaBatty requested changes
So excited to see this land, thanks heaps for putting this together. 

I think there may have been some issues with rebasing onto master, at least what I can see with files is sway-lsp. There was an API refactor that happened in between you starting this. The LSP files in this PR don't match up with the current file layout / API. Might be worth taking a look at rebasing those files again.

2022-12-21 18:32 UTC, emilyaherbert commented on sway-core/src/control_flow_analysis/flow_graph/mod.rs
> +// impl<'a, N, E, Ty, Ix> petgraph::visit::IntoEdgeReferences
Ah yes, thanks for catching this with all of the green on this PR!

2022-12-21 20:22 UTC, emilyaherbert commented
@JoshuaBatty I've added the changes you requested by dismissed you "request for changes" review as you're OOO. Feel free to ask for additional changes though if you see anything that I should address.

2022-12-22 00:38 UTC, mohammadfawaz approved these changes
Amazing work @emilyaherbert! Thank you so much for this. It will be make a lot of people happy 😄

2022-12-22 01:43 UTC, otrho approved these changes

2022-12-22 01:43 UTC, merged