feat: forc command to init/new workspace
FuelLabs/sway pull request #3418
Opened 2022-11-23 13:11 UTC by kayagokalp

closes #3405.

## TODO

- [ ] Documentation

2022-11-28 08:01 UTC, mitchmindtree requested changes
Thanks for jumping onto this! Just a couple suggestions

2022-11-28 08:01 UTC, mitchmindtree commented on forc/src/ops/forc_init.rs
> +            "Multiple types detected, please specify only one project type: \
```suggestion
            "Multiple types detected, please specify only one initialization type: \
```

2022-11-28 12:08 UTC, kayagokalp commented on forc/src/ops/forc_init.rs
> +enum ProjectType {
Yepp makes more sense, thanks 👍

2022-11-30 02:08 UTC, mitchmindtree approved these changes

2022-11-30 15:24 UTC, bingcicle approved these changes

2022-11-30 15:24 UTC, merged