Implement From trait for u64 for U128 & U256
FuelLabs/sway pull request #4581
Opened 2023-05-23 16:39 UTC by dmihal

## Description

Simple helper functions for easy conversion between big integers and `u64`.

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2023-07-13 15:54 UTC, anton-trunov requested changes

2023-07-13 15:54 UTC, anton-trunov commented on sway-lib-std/src/u128.sw
> +    }
Here, `into` may fail, but the Rust semantics says that the `From`/`Into` trait methods must not fail (see https://doc.rust-lang.org/std/convert/trait.From.html).

2023-07-13 15:54 UTC, anton-trunov commented on sway-lib-std/src/u256.sw
> +    }
Here, `into` may fail, but the Rust semantics says that the `From`/`Into` trait methods must not fail (see https://doc.rust-lang.org/std/convert/trait.From.html).

2023-07-21 13:26 UTC, IGI-111 commented
Superceded by #4829

2023-07-21 13:26 UTC, closed without merging