Fixes sha256 returning erroneous results.
FuelLabs/sway pull request #4617
Opened 2023-06-01 09:00 UTC by esdrubal

## Description

The bug fixed was caused by sha256 being called with a byte size greater than the string provided. This was caused by the intrinsic `__size_of` returning the size padded to the next word alignment.

This was fixed by introducing a new intrinsic `__size_without_padding_of` which does not return a padded size for strings.

Fixes #4491

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2023-06-01 11:43 UTC, IGI-111 requested changes
Nice find! I don't think it's a good idea to introduce this intrinsic though.

The bug here is on the standard library side, assuming that the memory footprint of a value is only made of significant data, which it should not assume.
But since padding isn't necessarily contiguous, the newly added intrinsic can't inform you accurately about the layout in every case, and I think that's misleading.

I also think std does not need this kind of help from the compiler, it should be able to figure out the layout of the significant data from the length and type in this case using a simple multiplication of the size of the underlying type and the number of elements with the guarantee that for non struct types, the values are contiguous.

I would however be favorable to introducing an intrinsic that does something like C++'s [`std::has_unique_object_representations`](https://en.cppreference.com/w/cpp/types/has_unique_object_representations) if it helps.

2023-06-12 16:57 UTC, esdrubal commented
The new changes fix the current `sha256` which is widely used, including in storage libraries.

I will work on adding a Rust like traits implementation for `Hash` and `Hasher` in another pull request. This will make sure places, where it is critical to have immutability of hashes between versions, can use this which probably is the case for storage libraries.

2023-06-12 22:35 UTC, IGI-111 approved these changes
Good enough as a quick fix while we redesign std :+1:

2023-06-12 23:24 UTC, JoshuaBatty approved these changes

2023-06-13 03:57 UTC, merged