feat: generate deployment artifacts with forc-deploy
FuelLabs/sway pull request #4913
Opened 2023-08-04 12:04 UTC by kayagokalp

## Description
closes #4744.

This PR adds deployment artifact serialization to forc-deploy. Basically each deployment info is saved as a json file in the out folder. So that users wont lose precious deployment information after closing their terminal.

An example deployment artifact can be seen below:
```json
{
  "transaction_id": "0xec27bb7a4c8a3b8af98070666cf4e6ea22ca4b9950a0862334a1830520012f5d",
  "salt": "0x9e35d1d5ef5724f29e649a3465033f5397d3ebb973c40a1d76bb35c253f0dec7",
  "network_endpoint": "http://127.0.0.1:4000",
  "chain_id": 0,
  "contract_id": "0x767eeaa7af2621e637f9785552620e175d4422b17d4cf0d76335c38808608a7b",
  "deployment_size": 68,
  "deployed_block_id": "0x915c6f372252be6bc54bd70df6362dae9bf750ba652bf5582d9b31c7023ca6cf"
}                                                                                                                                                                                                                     
```
Since serde serialization for `ContarctId` and other deployment related client/vm primitives do not emit 0x at the beginning i had to convert them to `String`s 0x prefixed. I feel like we can change human readable serialization to include 0x to all hex fields.

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2023-08-04 12:09 UTC, kayagokalp commented
After merging this and #4771, we will be closing #4723 and #4745

2023-08-06 23:35 UTC, JoshuaBatty requested changes

2023-08-06 23:35 UTC, JoshuaBatty commented on forc-plugins/forc-client/src/op/deploy.rs
> +                // Create a deployment articact.
```suggestion
                // Create a deployment artifact.
```

2023-08-07 10:18 UTC, kayagokalp commented on forc-plugins/forc-client/src/op/deploy.rs
> +                // Create a deployment articact.
🤦 Thanks!

2023-08-08 21:59 UTC, sdankel submitted a review, later dismissed

2023-08-10 23:29 UTC, JoshuaBatty commented
Nice work, this will be super handy for users. The code looks good. Would you mind also adding this to the docs, maybe showing the example of an generated artifacts and some information about where the json is saved etc..?

2023-08-15 16:21 UTC, kayagokalp commented
Added docs with example artifact, should be good to go!

2023-08-16 04:49 UTC, JoshuaBatty commented on docs/book/src/forc/plugins/forc_client/index.md
> +forc-deploy stores deployment details in 'out/deployments' folder in project root directory for each deployment. An example deployment artifact can be seen below:
```suggestion
forc-deploy saves the details of each deployment in the `out/deployments` folder within the project's root directory. Below is an example of a deployment artifact:
```

2023-08-16 14:57 UTC, eureka-cpu approved these changes
LGTM

2023-08-16 14:57 UTC, merged