Improve inline arguments formatting
FuelLabs/sway pull request #5283
Opened 2023-11-15 20:58 UTC by cr-fuel

## Description

Improve breaking method calls into multiple lines following Rust rules.

A two parts method call is never broken into multiple lines, longer chains are broken if they are long enough (counting their arguments).

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2023-11-15 22:00 UTC, JoshuaBatty requested changes

2023-11-15 22:00 UTC, JoshuaBatty commented on swayfmt/src/utils/language/expr/mod.rs
> +/// Weather this expression can be inlined if it is the sole argument of a
```suggestion
/// Whether this expression can be inlined if it is the sole argument of a
```

2023-11-15 23:02 UTC, sdankel submitted a review, later dismissed
Looks good, thanks!

2023-11-16 00:10 UTC, JoshuaBatty approved these changes

2023-11-16 07:32 UTC, sdankel approved these changes

2023-11-16 07:32 UTC, merged