Implements the `Eq` trait for `Option`
FuelLabs/sway pull request #5302
Opened 2023-11-26 23:23 UTC by brandonsurh

## Description
Closes #3542
Implements the `Eq` trait for `Option`. Also adds tests for the implementation.

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2023-11-26 23:23 UTC, brandonsurh commented
Will need help with adding assignees, adding labels, and requesting reviewers due to permissions.

2023-11-26 23:48 UTC, brandonsurh commented
Not sure why the `cargo-run-e2e-test` check is failing. However, it doesn't not seem related to the contents of this PR.

2023-11-27 07:02 UTC, bitzoic commented
> Not sure why the `cargo-run-e2e-test` check is failing. I don't think it's related to these changes, but I'm not certain.

Looks like this is a breaking change. You will need to replace the contract address in the e2e test script with `0xe2f370fb01c8c36a521093494a023ce2d7232398e5e88722164c42ec0303f381`.

<img width="635" alt="Screenshot 2023-11-27 at 10 02 01 AM" src="https://github.com/FuelLabs/sway/assets/54727135/3821e9d0-dba8-43b6-b940-6626bf1e96a5">

2023-11-27 08:06 UTC, Braqzen requested changes
I don't believe that we need to check the permutations anymore and all of these negations can probably be cleaned up too.

Besides that, I need to block this until all primitives are tested. An integer and bool are insufficient here despite the trait constraint.

Once all types are tested this will be good to merge

2023-11-27 08:08 UTC, Braqzen commented
> > Not sure why the `cargo-run-e2e-test` check is failing. I don't think it's related to these changes, but I'm not certain.
> 
> Looks like this is a breaking change. You will need to replace the contract address in the e2e test script with `0xe2f370fb01c8c36a521093494a023ce2d7232398e5e88722164c42ec0303f381`.
> 
> <img alt="Screenshot 2023-11-27 at 10 02 01 AM" width="635" src="https://private-user-images.githubusercontent.com/54727135/285749499-3821e9d0-dba8-43b6-b940-6626bf1e96a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzI2OTksIm5iZiI6MTcwMTA3MjM5OSwicGF0aCI6Ii81NDcyNzEzNS8yODU3NDk0OTktMzgyMWU5ZDAtZGJhOC00M2I2LWI5NDAtNjYyNmJmMWU5NmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA4MDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNDg2MWM0MjY1NTlhZTg5YmU0OGM4OWZjMTYzOTc0N2ZmODk1ZGQ3Zjk3MmQwNjA4ZTc3NTQwODM1MmQ1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1dNN-imDndym5-sbK4qNQvg-DgWWcG3EhboIoNaBthQ">

I don't believe this to be a breaking change. It extends the functionality but does not change the API.
Something somewhere else breaks, that's not a breaking change. That's a side effect of how we wrote the test suite. Once the API is changed for the user (ex. swap the order of parameters in a function) then that qualifies as a breaking change.

2023-11-27 08:42 UTC, bitzoic commented
> > > Not sure why the `cargo-run-e2e-test` check is failing. I don't think it's related to these changes, but I'm not certain.
> > 
> > 
> > Looks like this is a breaking change. You will need to replace the contract address in the e2e test script with `0xe2f370fb01c8c36a521093494a023ce2d7232398e5e88722164c42ec0303f381`.
> > <img alt="Screenshot 2023-11-27 at 10 02 01 AM" width="635" src="https://private-user-images.githubusercontent.com/54727135/285749499-3821e9d0-dba8-43b6-b940-6626bf1e96a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzI2OTksIm5iZiI6MTcwMTA3MjM5OSwicGF0aCI6Ii81NDcyNzEzNS8yODU3NDk0OTktMzgyMWU5ZDAtZGJhOC00M2I2LWI5NDAtNjYyNmJmMWU5NmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA4MDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNDg2MWM0MjY1NTlhZTg5YmU0OGM4OWZjMTYzOTc0N2ZmODk1ZGQ3Zjk3MmQwNjA4ZTc3NTQwODM1MmQ1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1dNN-imDndym5-sbK4qNQvg-DgWWcG3EhboIoNaBthQ">
> 
> I don't believe this to be a breaking change. It extends the functionality but does not change the API. Something somewhere else breaks, that's not a breaking change. That's a side effect of how we wrote the test suite. Once the API is changed for the user (ex. swap the order of parameters in a function) then that qualifies as a breaking change.

Any changes that can change an existing contract's bytecode and hash must be labeled as a breaking change.

2023-11-27 09:48 UTC, Braqzen commented
> > > > Not sure why the `cargo-run-e2e-test` check is failing. I don't think it's related to these changes, but I'm not certain.
> > > 
> > > 
> > > Looks like this is a breaking change. You will need to replace the contract address in the e2e test script with `0xe2f370fb01c8c36a521093494a023ce2d7232398e5e88722164c42ec0303f381`.
> > > <img alt="Screenshot 2023-11-27 at 10 02 01 AM" width="635" src="https://private-user-images.githubusercontent.com/54727135/285749499-3821e9d0-dba8-43b6-b940-6626bf1e96a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzI2OTksIm5iZiI6MTcwMTA3MjM5OSwicGF0aCI6Ii81NDcyNzEzNS8yODU3NDk0OTktMzgyMWU5ZDAtZGJhOC00M2I2LWI5NDAtNjYyNmJmMWU5NmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA4MDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNDg2MWM0MjY1NTlhZTg5YmU0OGM4OWZjMTYzOTc0N2ZmODk1ZGQ3Zjk3MmQwNjA4ZTc3NTQwODM1MmQ1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1dNN-imDndym5-sbK4qNQvg-DgWWcG3EhboIoNaBthQ">
> > 
> > 
> > I don't believe this to be a breaking change. It extends the functionality but does not change the API. Something somewhere else breaks, that's not a breaking change. That's a side effect of how we wrote the test suite. Once the API is changed for the user (ex. swap the order of parameters in a function) then that qualifies as a breaking change.
> 
> Any changes that can change an existing contract's bytecode and hash must be labeled as a breaking change.

I'm unsure whether I agree with that. Can you tell me where that reasoning comes from and where this was brought up?

2023-11-28 17:25 UTC, brandonsurh commented
> I don't believe that we need to check the permutations anymore and all of these negations can probably be cleaned up too.
> 
> Besides that, I need to block this until all primitives are tested. An integer and bool are insufficient here despite the trait constraint.
> 
> Once all types are tested this will be good to merge

Cleaned up the permutations and negations. Tests were rewritten and now include the following types that were listed as primitives in the Sway Book:

- u8
- u16
- u32
- u64
- u256
- str
- str[]
- bool
- b256

The only problem is with `Eq` trait when testing the `str[]` (String Array) type. The last commit gives the following error:
```
 error
             --> /home/brandon/sway/test/src/e2e_vm_tests/test_programs/should_pass/stdlib/option_eq/src/main.sw:119:24
              |
          117 |
          118 |     // Eq tests
          119 |     assert(str_option1 == str_option1);
              |                        ^^ Trait "Eq" is not implemented for type "str[4]".
          120 |     assert(str_option1 == str_option2);
              |
          ____
```

Not sure what is causing this, but will look into it. It's possible that I am just handling it incorrectly.

2023-11-29 02:13 UTC, brandonsurh commented
Decided to skip over the fixed-length string tests and remove them. They are not within the constraints of the `Eq` trait. Tests should be good now.

2023-11-30 15:57 UTC, bitzoic submitted a review, later dismissed

2023-11-30 17:37 UTC, Braqzen reviewed
Struct, enum, tuple and array tests?

2023-11-30 23:51 UTC, brandonsurh commented
> Struct, enum, tuple and array tests?

Wasn't sure if these were within the scope for testing because they aren't primitive types. Though you're right, it's probably a good idea to test them anyways. Tests with them pass, however, implementing the `eq` method for them come with some warnings about them not being used for some reason. They are most definitely called because if you remove them then the tests break. Because of this, I added `expected_warnings = 5` to the `test.toml` file.

```
          warning
            --> /home/brandon/sway/test/src/e2e_vm_tests/test_programs/should_pass/stdlib/option_eq/src/main.sw:14:5
             |
          12 |
          13 |   impl core::ops::Eq for StringArray {
          14 |       fn eq(self, other: Self) -> bool {
             |  _____-
          15 | |         from_str_array(self) != from_str_array(other)
          16 | |     }
             | |_____- This method is never called.
          17 |   }
             |
          ____

          warning
             --> /home/brandon/sway/sway-lib-core/src/ops.sw:536:5
              |
          534 |
          535 |       /// ```
          536 |       fn neq(self, other: Self) -> bool {
              |  _____-
          537 | |         (self.eq(other)).not()
          538 | |     }
              | |_____- This method is never called.
          539 |   }
              |
          ____

          warning
            --> /home/brandon/sway/test/src/e2e_vm_tests/test_programs/should_pass/stdlib/option_eq/src/main.sw:21:5
             |
          19 |
          20 |   impl core::ops::Eq for Array {
          21 |       fn eq(self, other: Self) -> bool {
             |  _____-
          22 | |         self[0] == other[0] && self[1] == other[1]
          23 | |     }
             | |_____- This method is never called.
          24 |   }
             |
          ____

          warning
            --> /home/brandon/sway/test/src/e2e_vm_tests/test_programs/should_pass/stdlib/option_eq/src/main.sw:27:5
             |
          25 |
          26 |   impl core::ops::Eq for MyStruct {
          27 |       fn eq(self, other: Self) -> bool {
             |  _____-
          28 | |         self.x == other.x
          29 | |     }
             | |_____- This method is never called.
          30 |   }
             |
          ____

          warning
            --> /home/brandon/sway/test/src/e2e_vm_tests/test_programs/should_pass/stdlib/option_eq/src/main.sw:34:5
             |
          32 |
          33 |   impl core::ops::Eq for Tuple {
          34 |       fn eq(self, other: Self) -> bool {
             |  _____-
          35 | |         self.0 == other.0 && self.1 == other.1
          36 | |     }
             | |_____- This method is never called.
          37 |   }
             |
          ____

            Compiled script "option_eq" with 5 warnings.
```

2023-12-01 11:10 UTC, Braqzen approved these changes

2023-12-01 15:19 UTC, brandonsurh commented on test/src/e2e_vm_tests/test_programs/should_pass/stdlib/option_eq/test.toml
> +expected_warnings = 5
That's a good evaluation. I think that would be the case too. The problem is that if there are warnings without this flag then the test fails. I don't think the testing suite accepts when there are warnings without them being specified in this manner.

2023-12-01 21:01 UTC, IGI-111 approved these changes

2023-12-03 04:10 UTC, brandonsurh commented
The recent PR #5210 that changes the way `impl` trait functions are handled breaks this PR. Will address this.

2023-12-03 05:15 UTC, merged