Add support recover key
FuelLabs/sway pull request #5419
Opened 2023-12-21 20:36 UTC by crodas

## Description

Fixes FuelLabs/forc#111

Add recover-public-key to forc-crypto

This function is ported from https://github.com/FuelLabs/forc-wallet/pull/152

This PR depends on FuelLabs/sway#5388

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2024-01-10 22:48 UTC, JoshuaBatty requested changes

2024-01-10 22:48 UTC, JoshuaBatty commented on forc-plugins/forc-crypto/src/keys/recover.rs
> +        "Blah blah blah""#]
Can we have something a bit more descriptive here?

2024-01-16 07:04 UTC, JoshuaBatty commented on forc-plugins/forc-crypto/src/keys/recover.rs
> +        "Blah blah blah""#]
Sure, i don't mind that change. I was referring to the blah blah blah part :)

2024-01-17 22:13 UTC, sdankel commented on forc-plugins/forc-crypto/src/args.rs
>  ///     vector of bytes
This comment is for the function below.

2024-01-17 22:13 UTC, sdankel commented on forc-plugins/forc-crypto/src/keys/get_public_key.rs
> +pub fn handler(arg: Arg) -> Result<serde_json::Value> {
It would be nice to add unit tests for this

2024-01-21 05:47 UTC, JoshuaBatty commented on forc-plugins/forc-crypto/src/args.rs
> +///  2. If it is an String and it happens to be a file path, its content will be returned
```suggestion
///  2. If it's a String and it happens to be a file path, its content will be returned
```

2024-01-21 05:48 UTC, JoshuaBatty commented on forc-plugins/forc-crypto/src/args.rs
> +///  3. If it is an String and it is "-", stdin is read
```suggestion
///  3. If it's a String and it is "-", stdin is read
```

2024-01-22 22:31 UTC, JoshuaBatty approved these changes

2024-01-22 23:19 UTC, sdankel approved these changes

2024-01-23 02:14 UTC, merged