Provide `__jmpb_ssp` intrinsic
FuelLabs/sway pull request #5576
Opened 2024-02-08 08:52 UTC by vaivaswatha

The new intrinsic `__jmpb_ssp(offset: u64)` jumps backwards, from the current value of `$ssp`, by a provided byte offset.

This intrinsic is necessary for dynamically loading and executing a contract.

Here's an example contract (taken from https://github.com/FuelLabs/ldc-testing) for dynamically loading another contract and transferring control to it. The "loadable" contract is the one used in the link above.

```
// to be compiled in release mode
contract;

abi MyContract {
    fn test_function(code_id: ContractId);
}

impl MyContract for Contract {
    fn test_function(code_id_p: ContractId) {
        let length = asm(code_id, length, word, ssp_saved) {
            // Allocate 32 bytes on the heap (we can't use the stack)
            addi word zero i32;
            aloc word;

            lw code_id fp i74;
           
            // Log the ContractID for debugging
            logd zero zero code_id word;

            // Load the entire contract with LDC
            csiz length code_id;
            // Save the old ssp
            move ssp_saved ssp;
            ldc code_id zero length;
            // return the ssp difference, to feed __jmpb_ssp.
            // This need not always be equal to `length` as `ldc` pads the `length`.
            sub length ssp ssp_saved;
            length: u64
        };
        __jmpb_ssp(length)
    }
}
```

The intrinsic generates code to do the following:
1. Subract offset from `$ssp`.
2. Subtract `$is` since `$jmp` adds it back.
3. Divide by 4 since `Jmp` multiplies by 4
4. Jump to the computed value.

Closes #5563

2024-02-16 17:50 UTC, IGI-111 requested changes
We're missing a documentation mention in `book/src/reference/compiler_intrinsics.md` but otherwise LGTM

2024-02-18 16:49 UTC, IGI-111 approved these changes

2024-02-21 03:56 UTC, IGI-111 approved these changes

2024-02-23 21:53 UTC, dmihal approved these changes

2024-02-23 21:53 UTC, merged