Enhance autocomplete generation
FuelLabs/sway pull request #5612
Opened 2024-02-14 19:53 UTC by crodas

This PR fixes #5474,

This PR enhances the autocomplete feature that is built-in ly forc. The first enhancement is to add support to generate a script for [fig](https://fig.io).

The second enhancement is to add support to let each plugin (automatically through cli_examples) dump its clap configuration. This configuration is shared to the main `forc` binary which creates a single autocomplete script for the requested shell that is also aware of every `plugin`. If a plugin uses `cli_examples!` macro this will automatically inherit this feature without any additional change.

~The third improvement, still under development, is to install automatically the autocomplete feature instead of printing to the stdout (to address https://github.com/FuelLabs/fuelup/issues/548)~ (This feature has been added on c7015d0c0ad13cd0fd9a88ea2ef8c4b19ad38f26)

## Description

## Checklist

- [x] I have linked to any relevant issues.
- [x]  I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2024-02-17 01:36 UTC, sdankel reviewed
Could you add instructions on how to test this? I couldn't get autocompletions showing up after doing the following:

```
$ cargo install --path forc
$ cargo install --path forc-plugins/forc-crypto
$ forc completions
```

2024-02-17 01:36 UTC, sdankel commented on forc-util/src/cli.rs
> +                    .unwrap_or_default(),
nit: it might be nice to move this to a helper function

2024-02-17 01:36 UTC, sdankel commented on forc-util/src/cli.rs
> +    pub fn to_clap(&self) -> clap::App<'_> {
Perhaps we should just store the original clap command

2024-02-17 01:36 UTC, sdankel commented on forc-util/src/cli.rs
> +    pub fn to_clap(&self) -> clap::Arg<'_> {
Perhaps we should just store the original clap arg

2024-02-17 01:36 UTC, sdankel commented on forc-util/src/cli.rs
> +                            .map(|x| PossibleValues {
Should we account for aliases and hidden args?

2024-02-17 01:36 UTC, sdankel commented on forc/src/cli/commands/completions.rs
> +    });
We should definitely ask users before writing to their shell configuration. We should also tell the user what files are being written to.

2024-02-17 01:36 UTC, sdankel commented on forc/src/cli/commands/completions.rs
> +        Target::Bash => Some(format!("{}/.bashrc", dir)),
On mac, this is `bash_profile`

Since this varies by OS, could we use a crate to get the right shell config file(s)?

2024-02-17 01:36 UTC, sdankel commented on forc/src/cli/commands/completions.rs
> +        let file = File::open(&file_path).expect("Open the shell config file");
Does this cause a panic? What does this look like to the user?

2024-02-17 01:38 UTC, sdankel commented on forc/src/cli/commands/completions.rs
> +                println!("Forc completions is already installed");
I'm getting this message even after removing `$HOME/.forc.autocomplete`

2024-02-17 01:41 UTC, sdankel requested changes
We definitely need to ask the user before modifying their shell config.

2024-02-17 01:44 UTC, sdankel reviewed
We should also have some unit tests for this.

2024-02-17 02:14 UTC, sdankel commented
I got it working by manually adding

It seems like there's an issue with autocompleting flags. For example, I would expect this: `forc crypto --ve` to give me the autocomplete suggestion: `forc crypto --version` but it doesn't.

It also displays it as `<version>` rather than `--version`

```
$ forc crypto
<help>          address         help            new-key         sha256
<version>       get-public-key  keccak256       parse-secret
```

I would also expect this: `forc crypto v` to suggest `forc crypto --version` as an autocomplete.

2024-02-17 02:19 UTC, sdankel commented on forc/src/cli/commands/completions.rs
> +                println!("Forc completions is already installed");
```
                println!("Forc completions is already installed for {shell}");
```

2024-02-17 02:20 UTC, sdankel commented on forc/src/cli/commands/completions.rs
> +    println!("Forc completions is installed successfully");
```suggestion
    println!("Forc completions were installed successfully at {shell_config_path}");
```

2024-02-17 02:20 UTC, sdankel commented on forc/src/cli/commands/completions.rs
> +    println!("\t The script is stored in {}", forc_autocomplete_path);
```suggestion
    println!("\t The script is stored at {}", forc_autocomplete_path);
```

2024-02-17 02:21 UTC, sdankel commented on forc/src/cli/commands/completions.rs
> +                println!("Forc completions is already installed");
If the completions script has been updated, the user should not see this message. They should see something like "Successfully updated for completions."

2024-06-17 01:56 UTC, JoshuaBatty commented
Closing, not high priority.

2024-06-17 01:56 UTC, closed without merging