Add support for fig completions
FuelLabs/sway pull request #5669
Opened 2024-02-26 16:56 UTC by crodas

## Description

This fixes https://github.com/FuelLabs/sway/issues/5474

This is the first part of #5612, which will be split into several smaller PRs

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2024-02-26 19:45 UTC, sdankel requested changes

2024-02-26 19:45 UTC, sdankel commented on forc-plugins/forc-crypto/src/main.rs
> +const ABOUT: &str = "Forc plugin for hashing arbitrary data";
Clap can also parse the About from a doc comment, so you don't have to pass it in.

```rust 
/// Forc plugin for hashing arbitrary data.
#[derive(Debug, Parser)]
#[clap(
    name = "forc-crypto",
    after_help = help(),
    version
)]
pub enum Command {
```

2024-02-26 19:45 UTC, sdankel commented on forc/src/cli/commands/completions.rs
> +enum Target {
Same comment: https://github.com/FuelLabs/sway/pull/5612#discussion_r1493095479

2024-02-26 19:45 UTC, sdankel commented on forc/src/cli/commands/completions.rs
> +    Fig,
Fig is not a shell, right? It's an autocomplete provider for other shells.

2024-02-26 19:53 UTC, sdankel reviewed
Could you share the steps for manually testing this with fig?

Is it possible to write unit tests for this? It would be good to assert that the correct autocompletions file is created for each target.

2024-04-02 00:46 UTC, JoshuaBatty submitted a review, later dismissed

2024-04-02 14:21 UTC, kayagokalp approved these changes
✅

2024-04-03 23:14 UTC, JoshuaBatty approved these changes

2024-04-04 18:29 UTC, kayagokalp approved these changes

2024-04-04 18:39 UTC, merged