fix some comments
FuelLabs/sway pull request #5680
Opened 2024-03-03 02:33 UTC by cuishuang

## Description

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2024-03-03 02:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FuelLabs/sway?pullRequest=5680) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FuelLabs/sway?pullRequest=5680) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FuelLabs/sway?pullRequest=5680) it.</sub>

2024-03-03 23:20 UTC, sdankel approved these changes

2024-03-07 18:19 UTC, IGI-111 submitted a review, later dismissed

2024-04-22 13:43 UTC, IGI-111 commented on forc-pkg/src/manifest/mod.rs
> +            bail!("Nested packages are not supported, please consider separating the nested package at {} from the package at {}, or if it makes sense consider creating a workspace.", nested_package.
This isn't a comment, it's an actual error message.
The test for this needs to be updated as well.

2024-04-28 05:31 UTC, kayagokalp requested changes
Hi, thanks for the PR. CI seems to be failing because you updated an error message but did not changed the test for that error message. So what you need to do make the pipeline green is changing the expected message at [the related test.toml](https://github.com/FuelLabs/sway/blob/master/test/src/e2e_vm_tests/test_programs/should_fail/forc/nested_package/test.toml).

2024-04-29 05:16 UTC, kayagokalp approved these changes
Thanks!

2024-04-29 15:31 UTC, IGI-111 approved these changes

2024-05-01 13:58 UTC, IGI-111 commented
Solve the merge conflicts and we should be able to merge this.

2024-05-03 07:18 UTC, kayagokalp approved these changes

2024-05-06 16:36 UTC, IGI-111 approved these changes

2024-05-06 16:38 UTC, IGI-111 commented
It's outdated again :sweat:

2024-05-08 06:59 UTC, xunilrj approved these changes

2024-05-08 17:49 UTC, IGI-111 commented
The HEAD is moving pretty fast so it's outdated again, please check the box that [allows edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) in this PR so that we can auto update it and it can be merged.

2024-05-08 18:20 UTC, sdankel approved these changes

2024-05-09 20:00 UTC, IGI-111 commented
I'm going to close this PR, please reopen one with a personal account fork and we'll get this merged.

2024-05-09 20:00 UTC, closed without merging