Improves DCA warnings after divergent expressions.
FuelLabs/sway pull request #5726
Opened 2024-03-13 08:26 UTC by esdrubal

## Description

DCA warnings were missing when methods call return in some places.

Changes e2e test runner to use file checker in tests with category runs.

Fixes https://github.com/FuelLabs/sway/issues/5666

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2024-03-17 21:49 UTC, ironcev requested changes
To the questions on the `contains_never` method, maybe it can be done as a different PR, but maybe also as the part of this PR, to extend DCA test for uninhabited types and the cases like the one in the code sample provided in the comment where the variable `s` even if used somewhere later will actually always be dead. I expect our DCA with the change in this PR will already behave like that.

In that case we could also close #3496 with this PR.

2024-03-17 21:49 UTC, ironcev commented on sway-core/src/type_system/info.rs
> +            | TypeInfo::Struct(_)
Is this completely correct? We can have uninhabited structs and enums. E.g., this code compiles without errors, as it should:
```Sway
script;

struct S {
    x: !,
}

fn main() -> u64 {
    let s = S { x: { return 0u64; } };    
    0
}
```

2024-03-17 21:49 UTC, ironcev commented on sway-core/src/type_system/info.rs
> +            | TypeInfo::Ptr(_)
Also here, `Ptr`, `Slice`, `Alias`, and `Ref`. If the types they point to or contain or alias contain `Never` then I think they also cannot be inhabited.

2024-03-17 21:49 UTC, ironcev commented on sway-core/src/type_system/info.rs
> +    pub fn contains_never(&self, engines: &Engines) -> bool {
Perhaps calling this method `is_uninhabited`? `contains_never` sounds to me more like a _way_ to make a type uninhabited, but if I think about a type property the sentence "type.is_uninhabited()` sounds more like what that type _is_, which property it has.

2024-04-11 08:01 UTC, xunilrj commented on test/src/e2e_vm_tests/test_programs/should_pass/return_in_strange_positions/src/main.sw
>          break;
Shouldn´t this break also be unreachable? Actually.... thee whole body.

2024-04-11 08:05 UTC, xunilrj commented on test/src/e2e_vm_tests/test_programs/should_pass/return_in_strange_positions/src/main.sw
>          break;
This is what rustc returns
```
warning: unreachable block in `if` or `while` expression
 --> src/main.rs:2:22
  |
2 |     while {return 1} {}
  |            --------  ^^ unreachable block in `if` or `while` expression
  |            |
  |            any code following this expression is unreachable
  |
  = note: `#[warn(unreachable_code)]` on by default
```

2024-04-11 08:08 UTC, xunilrj commented on test/src/e2e_vm_tests/test_programs/should_pass/return_in_strange_positions/src/main.sw
>      let _ = Enum_multivariant::B((return 42, return 43));
and here.... 

```
warning: unreachable call
 --> src/main.rs:6:5
  |
6 |     A::A({return 1})
  |     ^^^^  -------- any code following this expression is unreachable
  |     |
  |     unreachable call
  |
  = note: `#[warn(unreachable_code)]` on by default
```

Although the "call" is the rustic error, is horrible.

2024-04-11 08:10 UTC, xunilrj approved these changes

2024-04-11 13:44 UTC, xunilrj approved these changes

2024-04-11 14:14 UTC, IGI-111 approved these changes

2024-04-11 14:36 UTC, merged