docs: add troubleshooting for slow performance
FuelLabs/sway pull request #5794
Opened 2024-03-27 18:36 UTC by hummusonrails

## Description

Add a troubleshooting section for slow performance in the LSP server advising users on steps to mediate it.

## Checklist

- [ ] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2024-03-27 19:12 UTC, sdankel requested changes
~~This has already been done: https://fuellabs.github.io/sway/v0.52.0/book/lsp/troubleshooting.html~~

Ah sorry I didn't see that you were just adding to the page.

2024-03-27 19:14 UTC, sdankel commented on docs/book/src/lsp/troubleshooting.md
> +kill pid # Replace pid with the PID of the older LSP server
This can just be one command: `pkill forc-lsp`

2024-03-27 19:16 UTC, sdankel commented on docs/book/src/lsp/troubleshooting.md
> +kill pid # Replace pid with the PID of the older LSP server
```suggestion
pkill forc-lsp
```

2024-03-29 05:07 UTC, sdankel approved these changes

2024-04-02 18:43 UTC, sarahschwartz approved these changes

2024-04-02 18:50 UTC, merged