Allow conversions between native u types and U128
FuelLabs/sway pull request #5825
Opened 2024-04-03 09:51 UTC by SwayStar123

## Description
Adds impl From<u8,u16,u32,u64> for U128

Partially addresses #5797 

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2024-04-04 05:46 UTC, SwayStar123 commented
Blocked by #5826

2024-04-16 02:29 UTC, bitzoic requested changes

2024-04-16 02:29 UTC, bitzoic commented on sway-lib-std/src/u128.sw
> +    ///
The examples are missing imports

2024-04-16 02:29 UTC, bitzoic commented on sway-lib-std/src/u128.sw
> +    /// Casts a `u8` to a `U128`.
```suggestion
    /// Converts a `u8` to a `U128`.
```

2024-04-18 15:29 UTC, K1-R1 requested changes

2024-04-18 15:29 UTC, K1-R1 commented on sway-lib-std/src/u128.sw
> +    /// Casts a `u32` to a `U128`.
```suggestion
    /// Converts a `u32` to a `U128`.
```

2024-04-22 15:59 UTC, K1-R1 approved these changes

2024-04-23 02:46 UTC, bitzoic approved these changes

2024-04-24 11:54 UTC, merged