Added --bech-32 flag to forc contract-id command
FuelLabs/sway pull request #5943
Opened 2024-05-02 02:34 UTC by ADTmux

## Description
Issue : [https://github.com/FuelLabs/sway/issues/5842](url)

## Checklist

- [x] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2024-05-02 02:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FuelLabs/sway?pullRequest=5943) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FuelLabs/sway?pullRequest=5943) before we can accept your contribution.<br/><hr/>**Amit Dave** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FuelLabs/sway?pullRequest=5943) it.</sub>

2024-05-02 02:39 UTC, ADTmux commented
working on updating docs. Please feel free to let me know if any other areas need to be updated as well!

2024-05-02 19:44 UTC, kayagokalp requested changes
Looking good! A possible issue with the dependency you added, so blocking for now as I need to make sure some stuff first. If that is the case I will provide you more guidance how to move around the issue with the dependency

2024-05-02 19:44 UTC, kayagokalp commented on forc/src/cli/commands/contract_id.rs
> +    // flag to display contract-id in bech32 format
```suggestion
    // Flag to display contract-id in bech32 format
```

2024-05-02 19:44 UTC, kayagokalp commented on forc/Cargo.toml
> +fuels-core = { workspace = true }
This dependency here will likely create an issue for us. Due to our internal procedures we require forc not to depend on sdk. We should be able to move around this somehow. I will think about a different way of doing this but first I wanted to make sure this is not allowed by our CI.

2024-05-02 19:46 UTC, kayagokalp commented
Also please run `cargo fmt` so that CI fails go away :) and make sure to run cargo build and commit the cargo.lock file since you added a depenedncy cargo.lock should be changed. But that is not commited here.

2024-05-04 02:28 UTC, ADTmux commented
@kayagokalp I did see the fact that we are generating the documentation for all forc commands in the Sway Book by running `forc --help`, but could I get any pointers to any past PRs, or as to how we are doing that? I want to add the `--bech32` in the Sway Book.

2024-05-04 02:35 UTC, kayagokalp commented
> @kayagokalp I did see the fact that we are generating the documentation for all forc commands in the Sway Book by running `forc --help`, but could I get any pointers to any past PRs (of how the html files are built), or as to how we are doing that? I want to add the `--bech32` in the Sway Book.  

Hey, no worries about that we have a mdbook preprocessor that automatically does that. So it is done via CI not manually

2024-08-29 22:47 UTC, closed without merging