TryFrom< B512 > for b256, u256
FuelLabs/sway pull request #6010
Opened 2024-05-14 14:21 UTC by SwayStar123

## Description
Adds TryFrom implementation for b256 and u256 from B512

partially addresses #5797

## Checklist

- [x] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2024-05-16 09:26 UTC, K1-R1 submitted a review, later dismissed

2024-05-16 09:55 UTC, bitzoic requested changes

2024-05-16 09:55 UTC, bitzoic commented on sway-lib-std/src/primitive_conversions/b256.sw
> +    /// If the high bits of the `B512` are not zero, the conversion will fail.
```suggestion
    /// # Additional Information
    /// 
    /// If the high bits of the `B512` are not zero, the conversion will fail.
```

2024-05-16 09:55 UTC, bitzoic commented on sway-lib-std/src/primitive_conversions/u256.sw
> +    /// If the high bits of the `B512` are not zero, the conversion will fail.
```suggestion
    /// # Additional Information
    ///
    /// If the high bits of the `B512` are not zero, the conversion will fail.
```

2024-05-17 10:52 UTC, K1-R1 approved these changes

2024-05-19 21:56 UTC, sdankel reviewed
I'm curious why this is going in `std` rather than `core`?

2024-05-20 02:57 UTC, bitzoic commented
> I'm curious why this is going in `std` rather than `core`?

`TryFrom` is only included in `std`

2024-05-21 03:02 UTC, bitzoic approved these changes

2024-05-21 05:28 UTC, merged