Change forc doc --manifest-path to forc doc --path
FuelLabs/sway pull request #6109
Opened 2024-06-11 15:41 UTC by alexanderblv

## Description
Closes https://github.com/FuelLabs/sway/issues/5789

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2024-06-11 15:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FuelLabs/sway?pullRequest=6109) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FuelLabs/sway?pullRequest=6109) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FuelLabs/sway?pullRequest=6109) it.</sub>

2024-06-11 18:10 UTC, kayagokalp requested changes
Hello, thanks for the PR. It seems like you just updated docs and readme, not the command itself.

https://github.com/FuelLabs/sway/blob/24d03f4e9fe13672961bbe696861a99508fa521a/forc-plugins/forc-doc/src/cli.rs#L26

2024-06-12 10:32 UTC, alexanderblv commented
> Hello, thanks for the PR. It seems like you just updated docs and readme, not the command itself.
> 
> https://github.com/FuelLabs/sway/blob/24d03f4e9fe13672961bbe696861a99508fa521a/forc-plugins/forc-doc/src/cli.rs#L26

I understand correctly that I have to update `manifest_path` in all sway files?

2024-06-13 09:39 UTC, IGI-111 submitted a review, later dismissed

2024-06-13 16:39 UTC, sdankel requested changes
I would prefer to make `--path` a shorthand for `--manifest-path` (keeping both as valid CLI flags) so as not to break any existing users.

2024-06-16 08:51 UTC, alexanderblv commented
> I would prefer to make `--path` a shorthand for `--manifest-path` (keeping both as valid CLI flags) so as not to break any existing users.

So you want to keep both run as valid?
`run: forc doc --manifest-path ./sway-lib-std`
`run: forc doc --path ./sway-lib-std`

I'm not sure if the duplicates will lead to good code performance, but if you think so, then I'll do it.

2024-06-18 00:50 UTC, sdankel requested changes
> > I would prefer to make `--path` a shorthand for `--manifest-path` (keeping both as valid CLI flags) so as not to break any existing users.
> 
> So you want to keep both run as valid? `run: forc doc --manifest-path ./sway-lib-std` `run: forc doc --path ./sway-lib-std`
> 
> I'm not sure if the duplicates will lead to good code performance, but if you think so, then I'll do it.

It shouldn't affect the code performance at all. You can use clap's [alias](https://docs.rs/clap/latest/clap/struct.Arg.html#method.alias):

```
    #[clap(long, alias="manifest-path")]
    pub path: Option<String>,
```

Please fix the compilation errors. You need to update `manifest_path` in the other places it is used.

2024-06-24 15:46 UTC, kayagokalp requested changes
Current ci.yml file is invalid, I suggested the correct version of it. But also I think we should not test whole sdk-harness twice just to see that a flag is working with different alias to preserve some valuable CI time. Let's keep the addition to the code to support it for users but remove it from ci. I think @sdankel originally wanted you to add the support to the code not to CI but pinging her in any case.

2024-06-24 15:46 UTC, kayagokalp commented on .github/workflows/ci.yml
>          run: forc doc --manifest-path ./sway-lib-std
```suggestion
        run: |
          forc doc --path ./sway-lib-std
          forc doc --manifest-path ./sway-lib-std
```

2024-06-24 15:46 UTC, kayagokalp commented on .github/workflows/gh-pages.yml
> +        run: forc doc --path ./sway-lib-std
```suggestion
        run: |
          forc doc --path ./sway-lib-std
          forc doc --manifest-path ./sway-lib-std
```

2024-06-24 15:47 UTC, kayagokalp requested changes

2024-06-24 15:47 UTC, kayagokalp commented on .github/workflows/gh-pages.yml
>          run: forc doc --manifest-path ./sway-lib-std
```suggestion
        run: |
          forc doc --path ./sway-lib-std
          forc doc --manifest-path ./sway-lib-std
```

2024-06-24 16:25 UTC, kayagokalp commented on forc-plugins/forc-doc/src/cli.rs
> +    pub path: Option<String>,
We can probably use, @sdankel's suggestion here:

```suggestion
    #[clap(long, alias="manifest-path")]
    pub path: Option<String>,
```

2024-06-24 16:26 UTC, kayagokalp requested changes

2024-06-24 16:26 UTC, kayagokalp commented on forc-plugins/forc-doc/src/cli.rs
> +    pub path: Option<String>,
We can probably use, @sdankel's suggestion here:

```suggestion
    #[clap(long, alias="manifest-path")]
    pub path: Option<String>,
```

2024-06-24 17:27 UTC, sdankel commented
I absolutely agree with  @kayagokalp , we should not run forc-doc twice in CI. This code still doesn't compile, so I'm going to close this PR. This isn't really close to what we're looking for and I want to leave the opportunity for another contributor to pick up this task.

2024-06-24 17:27 UTC, closed without merging