Counter Example Doc Update
FuelLabs/sway pull request #6164
Opened 2024-06-20 17:59 UTC by Chester-King

## Description
Linked the building and deployment doc and added the commands to enable developers in quickly building and deploying the contracts

### Motivation
To enable new developers to quickly deploy contracts from templates

2024-06-20 17:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FuelLabs/sway?pullRequest=6164) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FuelLabs/sway?pullRequest=6164) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FuelLabs/sway?pullRequest=6164) it.</sub>

2024-06-21 06:23 UTC, IGI-111 requested changes

2024-06-21 06:23 UTC, IGI-111 commented on docs/book/src/examples/counter.md
> +// Deploys the contract
```suggestion
# Deploys the contract
```

2024-06-21 21:52 UTC, sdankel commented on docs/book/src/examples/counter.md
> +the following commands will quickly help you in build and deploy the above contract - for detailed tutorial for this refer to [Building and Deploying](https://docs.fuel.network/guides/contract-quicks
```suggestion
The following commands will help you quickly build and deploy the above contract. For a detailed tutorial, refer to [Building and Deploying](https://docs.fuel.network/guides/contract-quickstart/#building-the-contract).
```

2024-06-21 21:52 UTC, sdankel commented on docs/book/src/examples/counter.md
> +### Building and deployment
```suggestion
### Build and deploy
```

2024-06-21 21:53 UTC, sdankel commented on docs/book/src/examples/counter.md
> +# Builds the contract
```suggestion
# Build the contract
```

2024-06-21 21:53 UTC, sdankel commented on docs/book/src/examples/counter.md
> +# Deploys the contract
```suggestion
# Deploy the contract
```

2024-06-21 21:53 UTC, sdankel commented on docs/book/src/examples/counter.md
> +It will return you the contract ID.
```suggestion
```

2024-06-21 22:02 UTC, Chester-King commented
Hey @sdankel @IGI-111 thanks for the suggested changes 
As I am going through the fuel docs - I'll start putting PRs for places which will be beneficial to a beginner and an experienced developer alike and help them move forward with building on fuel.

2024-06-23 12:43 UTC, IGI-111 approved these changes

2024-06-23 23:57 UTC, JoshuaBatty commented
@Chester-King would you mind fixing the markdown lint so we can get this merged? Thanks.

2024-06-24 10:30 UTC, IGI-111 requested changes
You just reverted all the requested changes.

2024-06-24 10:37 UTC, Chester-King commented
@IGI-111  Apologies - fixing

2024-06-24 10:45 UTC, IGI-111 approved these changes

2024-06-24 17:33 UTC, sdankel approved these changes

2024-06-24 17:35 UTC, kayagokalp approved these changes
I re-ran the check links job, it seems like a link is found to be dead but i can access it. Maybe it was flaky.

2024-06-24 17:38 UTC, merged