update all the deps
FuelLabs/sway pull request #6190
Opened 2024-06-25 20:04 UTC by rvcas

## Description

closes #6179

I ran `cargo upgrade` and then had to fix a few things because `syn` and `annotate-snippets` had breaking changes.

I can update the `fuel-*` deps as well but some of the errors were a bit cryptic for me still cause I have yet to sort out how all the things glue together.

I'm still having some issues with `forc-wallet` which was bumped in the lock file to `0.8.1` from `0.8.0`.

There was some odd version mismatch between `lsp_types` and `tower_lsp::lsp_types`. I figured it's probably best to just use the `lsp_types` that is re-exported by tower-lsp so that we can avoid the version mismatch entirely.

## Checklist

- [x] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2024-06-25 20:05 UTC, rvcas commented on sway-ir/sway-ir-macros/src/lib.rs
> +    let nested = attr
This was a bit of a struggle but I think I got it to something reasonable. Not sure yet how to confirm that this change is safe.

2024-06-25 20:52 UTC, kayagokalp commented
Hey @rvcas https://github.com/FuelLabs/sway/pull/6187 will update forc-wallet to v0.8.1

2024-06-25 20:57 UTC, kayagokalp requested changes
Hey @rvcas https://github.com/FuelLabs/sway/pull/6187 will update forc-wallet to v0.8.1. Also it might be nice to do this to https://github.com/FuelLabs/sway/tree/master/test/src/sdk-harness as well. This is not part of the workspace to prevent some intra repo dependency we have between rust sdk and sway repo. So it is separate from the workspace and if you ran cargo update on root of this workspace, it won't get updated. RC for that for now to prevent getting this merged accidentally but if you already did that and there is no diff let me know, will pull this back!

2024-06-26 06:29 UTC, JoshuaBatty commented on sway-lsp/src/handlers/request.rs
> +    params: &tower_lsp::lsp_types::InitializeParams,
these are getting pretty long now. It's probably nicer so either include the type in the use statement directly or `use tower_lsp::lsp_types::{self, .... }` to keep these how they were.

2024-06-27 14:02 UTC, kayagokalp commented
#6187 is merged and should help about forc-wallet issue you were having :)

2024-10-28 00:44 UTC, kayagokalp commented
closing this as it is no longer relevant

2024-10-28 00:44 UTC, closed without merging