Increase Safety when introspecting transaction outputs
FuelLabs/sway pull request #6414
Opened 2024-08-14 09:44 UTC by bitzoic

## Description

When using the`outputs.sw` library of the std-lib, if a bad input was given to the functions or a transaction did not exist, the functions would revert. Instead, they now return options so errors may be caught.

## Notes

This PR updates `output_count()` to return a `u16` which follows the fuel specifications.

## Breaking

There are a number of breaking changes in function return types.

- `output_type()` now returns an `Option<Output>`.
Before:
```sway
let my_output_type: Output = output_type(0);
```
After:
```sway
let my_output_type: Output = output_type(0).unwrap();
```

- `output_pointer()` now returns an `Option<u64>`.
Before:
```sway
let my_output_pointer: u64 = output_pointer(0);
```
After:
```sway
let my_output_pointer: u64 = output_pointer(0).unwrap();
```

- `output_count()` now returns a `u16`.
Before:
```sway
let output_count: u64 = output_count();
```
After:
```sway
let my_output_count: u16 = output_count();
```

- `output_amount()` now returns an `Option<u64>`.
Before:
```sway
let my_output_amount: u64 = output_amount(0);
```
After:
```sway
let my_output_amount: Option<u64> = output_amount(0).unwrap();
```

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2024-08-15 21:03 UTC, K1-R1 requested changes

2024-08-16 00:33 UTC, JoshuaBatty commented on sway-lib-std/src/asset.sw
> +        if let Output::Variable = output_type(index).unwrap() {
Can we match on the Some types instead unwrapping?

```rust
if let Some(Output::Variable) = output_type(index) {
    if let Some(0) = output_amount(index) {
        ...
    }
}
```

2024-08-16 08:28 UTC, alfiedotwtf submitted a review, later dismissed

2024-08-16 09:13 UTC, SwayStar123 approved these changes

2024-08-16 09:32 UTC, K1-R1 approved these changes

2024-08-16 17:02 UTC, IGI-111 approved these changes

2024-08-16 21:26 UTC, merged