ci: Benchmark with codspeed
FuelLabs/sway pull request #6478
Opened 2024-08-28 19:05 UTC by sdankel

## Description

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2024-08-28 22:20 UTC, kayagokalp approved these changes

2024-08-28 23:28 UTC, JoshuaBatty requested changes

2024-08-29 00:15 UTC, sdankel commented on .github/workflows/bench-lsp.yml
> -      - sway-core/**
I believe it's meant to run on merges to master to create the new baseline for comparison.

2024-08-29 00:17 UTC, sdankel commented on .github/workflows/benchmark.yml
> +  pull_request:
```suggestion
  pull_request:
    paths: 
       - forc-plugins/forc-lsp/** 
       - sway-lsp/** 
       - forc-pkg/** 
       - sway-core/**
```

2024-08-29 01:19 UTC, kayagokalp commented
In a separate PR, maybe we should also get sway compiler benchmarks to this system as well, rather than collecting them in a separate website (which I believe happens right now). This way the compiler team will also be able to see their PR's effects more easily.

2024-08-29 01:48 UTC, sdankel commented
> In a separate PR, maybe we should also get sway compiler benchmarks to this system as well, rather than collecting them in a separate website (which I believe happens right now). This way the compiler team will also be able to see their PR's effects more easily.
> 
> I guess we should first experiment with our own benchmarks and can recommend them if it looks good

This will run and upload all criterion benchmarks to codspeed. I believe the compiler benchmarks aren't run with criterion because they're measuring things other than speed (memory, bytecode size, etc)

2024-08-29 02:00 UTC, sdankel commented
Closing in favor of https://github.com/FuelLabs/sway/pull/6481

I'm not sure why, but it randomly started failing on this PR and works on the new branch with the same changes.

2024-08-29 02:00 UTC, closed without merging