Move all crate dependencies to the workspace Cargo.toml (#6179)
FuelLabs/sway pull request #6563
Opened 2024-09-18 07:19 UTC by alfiedotwtf

## Description

For #6179, PR #6501 kept bumping into errors as it was doing too many things, so I've split that PR into multiple PRs. This is the first, and the only thing it does is move all of the various `Cargo.toml` dependencies into the single workspace `Cargo.toml`.

Future PRs will:
- Update dependency versions
- Update code that breaks from the version bumps

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [x] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2024-09-19 23:26 UTC, JoshuaBatty requested changes

2024-09-19 23:26 UTC, JoshuaBatty commented on Cargo.lock
> - "forc-tracing 0.63.6",
probably best to do a search and replace to change all occurrences of 0.63.5 back to 0.63.6

2024-09-20 02:05 UTC, JoshuaBatty approved these changes
nice one

2024-09-20 17:22 UTC, sdankel approved these changes

2024-09-20 23:48 UTC, merged