Merge std and core libraries
FuelLabs/sway pull request #6729
Opened 2024-11-18 06:54 UTC by SwayStar123

## Description
Merges the two libraries. They were initially separate to separate the core logic and fuel vm specific functionality, but that separation is no longer maintained so having a merged library is better.

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2025-03-07 13:17 UTC, xunilrj commented on forc-pkg/src/pkg.rs
> -    if !core_added {
Shouldn´t this method do the same thing, but for the `std` lib?

2025-03-07 13:22 UTC, xunilrj commented on forc-plugins/forc-doc/src/tests/data/impl_traits_generic/Forc.toml
> +ops = { path = "../ops" }
Why `ops` here and not `std`?

2025-03-07 14:02 UTC, SwayStar123 commented on forc-plugins/forc-doc/src/tests/data/impl_traits_generic/Forc.toml
> +ops = { path = "../ops" }
previously the test used core as it wasnt that large, so the hardcoded values in the test werent that long. but with the new std its comically long and unnecessary.

2025-03-07 14:07 UTC, SwayStar123 commented on forc-pkg/src/pkg.rs
> -    if !core_added {
does the implicitly_include_std_if_missing function not do it?

2025-03-07 16:58 UTC, xunilrj commented on sway-lib-std/src/ops.sw
> +impl u16 {
If we are moving this, why to `ops.sw` and not to `primitives.sw`? I imagine it's the ordering of these modules.

2025-03-07 17:24 UTC, SwayStar123 commented on sway-lib-std/src/ops.sw
> +impl u16 {
the implementation uses the eq operation

2025-03-10 09:45 UTC, IGI-111 requested changes
I'm going through the PR and it looks fine so far but I want to block merging this until we have the migrations for it merged and released.

2025-03-11 12:58 UTC, jjcnn requested changes
Truly a Herculian effort on this one!

I've added a few comments. There shouldn't be much work in them, so there should be time to do them before the release.

The ones about using the reduced std libs can be left for a separate issue if needed.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/language/nested_while_and_if/src/main.sw
> +use std::*;
This line of code doesn't actually do anything, so we should be able to remove it.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/language/new_allocator_test/src/main.sw
> +use std::*;
Same issue here: The line doesn't do anything, and can be removed.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/Forc.toml
> +std = { path = "../../../../../../../sway-lib-std" }
Only whitespace changes in this file.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/Forc.toml
> +std = { path = "../../../../../../../sway-lib-std" }
If `sway-lib-std-assert` doesn't contain everything this test needs, then maybe there's a case for creating a new reduced std library containing stuff related to contract calls and deployment?

Probably best to do that as a separate issue.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/test_abis/abi_with_tuples/Forc.toml
> +std = { path = "../../../../reduced_std_libs/sway-lib-std-assert" }
I think this test only needs sway-lib-std-core, not sway-lib-std-assert.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/test_abis/array_of_structs_abi/Forc.toml
> +std = { path = "../../../../../../../sway-lib-std" }
I think this test only needs sway-lib-std-core, not the full std.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/test_abis/auth_testing_abi/Forc.toml
> +std = { path = "../../../../../../../sway-lib-std" }
I think this test only needs sway-lib-std-core, not the full std.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/test_abis/balance_test_abi/Forc.toml
> +std = { path = "../../../../../../../sway-lib-std" }
I think this test only needs sway-lib-std-core, not the full std.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/test_abis/storage_access_abi/Forc.toml
> +std = { path = "../../../../../../../sway-lib-std" }
I think this test only needs sway-lib-std-core, not the full std.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/test_abis/storage_enum_abi/Forc.toml
> +std = { path = "../../../../../../../sway-lib-std" }
I think this test only needs sway-lib-std-core, not the full std.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_tuples_contract/Forc.toml
> +std = { path = "../../../../reduced_std_libs/sway-lib-std-assert" }
I think this test only needs sway-lib-std-core.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/array_of_structs_contract/Forc.toml
> +std = { path = "../../../../../../../sway-lib-std" }
Probably only needs sway-lib-std-core.

2025-03-11 12:58 UTC, jjcnn commented on test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/nested_struct_args_contract/Forc.toml
> +std = { path = "../../../../reduced_std_libs/sway-lib-std-assert" }
Probably only needs sway-lib-std-core.

2025-03-11 12:58 UTC, jjcnn commented on test/src/sdk-harness/test_projects/string_slice/string_slice_predicate/Forc.toml
> +std = { path = "../../../../../../sway-lib-std" }
Probably only needs sway-lib-std-core.

2025-03-11 13:13 UTC, SwayStar123 commented on sway-core/src/semantic_analysis/ast_node/declaration/auto_impl/abi_encoding.rs
> +        {
This isnt so much about them being former members of core, but that they are the dependencies of the codec library. I will add a comment

2025-03-12 10:41 UTC, jjcnn approved these changes
Changing my review status to approved. 

The one change that was definitely needed was comments in abi_encoding.rs, which have been added.

My remaining review comments are nits.

2025-03-12 12:40 UTC, IGI-111 approved these changes

2025-03-12 12:58 UTC, bitzoic approved these changes
I would have liked to see more edge cases covered(zero and max values) in the inline tests but these can be added afterward

2025-03-12 22:52 UTC, merged