Rework and fix associated const visibility for impl items
FuelLabs/sway pull request #6785
Opened 2024-12-11 11:40 UTC by tritao

## Description

This PR fixes associated constant visiblity checking for impl items.

The behaviour is that consts declared in traits are always considered public, whereas if they are declared anywhere else they are private unless they have the pub modifier.

```sway
library;

pub struct I8 {
    underlying: u8,
}

impl I8 {
    const MIN: Self = Self {
        underlying: u8::min(),
    };
}

trait Foo {
    fn foo();
}

impl Foo for I8 {
    fn foo() {
        let x = Self::MIN;
        log(x);
    }
}
```

Fixes https://github.com/FuelLabs/sway/issues/6772.

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [x] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2025-02-03 13:13 UTC, jjcnn requested changes

2025-02-03 13:13 UTC, jjcnn commented on sway-core/src/semantic_analysis/symbol_resolve_context.rs
> +    visibility_level: Visibility,
I don't understand this comment, and I'm finding it difficult to understand what `visibility_level` is supposed to represent. Could you elaborate a bit (ideally in this comment, or in the PR description)?

2025-02-04 14:03 UTC, jjcnn requested changes
I'm still confused by what `visibility_level` means.

It also took me a while to figure out what problem this PR is supposed to solve in the first place. The PR deccription just links to an issue, but that issue only consists of an example program with no description of what the compiler does incorrectly for that program.

2025-04-29 22:06 UTC, sdankel approved these changes

2025-04-30 00:42 UTC, JoshuaBatty approved these changes

2025-04-30 03:01 UTC, merged