Add `forc-migrate` tool
FuelLabs/sway pull request #6790
Opened 2024-12-16 13:44 UTC by ironcev

## Description

This PR introduces `forc-migrate`, a Forc tool for migrating Sway projects to the next breaking change version of Sway.

The tool addresses two points crucial for code updates caused by breaking changes:
- it informs developers about the breaking changes and **assists in planing and executing** the migration.
- it **automatically changes source code** where possible, reducing the manual effort needed for code changes.

Besides adding the `forc-migrate` tool, the PR:
- extends `Diagnostic` to support migration diagnostics aside with errors and warnings.
- changes `swayfmt` to support generating source code from arbitrary lexed trees. The change is a minimal one done only in the parts of `swayfmt` that are executed by migration steps written in this PR. Adapting `swayfmt` to fully support arbitrary lexed trees will be done in #6779.

The migration for the `references` feature, migrating `ref mut` to `&mut`, is added only temporarily, to demonstrate the development and usage of automatic migrations that alter the original source code. This migration will be removed before the next breaking change release, because the `references` feature will not be a part of it.

The intended usage of the tool is documented in detail in the "forc migrate" chapter of The Sway Book: _Forc reference > Plugins > forc_migrate_.

We expect the `forc-migrate` to evolve based on the developers feedback. Some of the possible extensions of the tool are:
- adding additional CLI options, e.g., for executing only specific migration steps, or ignoring them.
- passing parameters to migration steps from the CLI.
- migrating workspaces.
- migrating other artifacts, e.g., Forc.toml files or contract IDs.
- migrating between arbitrary versions of Sway.
- migrating SDK code.
- etc.
 
`forc-migrate` also showed a clear need for better infrastructure for writing static analyzers and transforming Sway code. The approach used in the implementation of this PR should be seen as a pragmatic beginning, based on what we currently have. Some future options are discussed in #6779.

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [x] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

2024-12-17 14:32 UTC, ironcev commented
To try out the `forc migrate` tool locally:
1. Pull and checkout the `ironcev/forc-migrate-tool` branch.
1. Install the tool from the Sway repository: `cargo install --path ./forc-plugins/forc-migrate`

For the detailed documentation on migration and the usage of the tool see the [scripts/mdbook-forc-documenter/examples/forc_migrate.md](https://github.com/FuelLabs/sway/pull/6790/files#diff-a0612fb4572e61bc83c53eac95d93b0e44ec8553cbc3d834e41936a851ab3b88) in this PR.

2025-01-06 13:40 UTC, IGI-111 requested changes
The tool seems fine, but the migration for https://github.com/FuelLabs/sway/issues/6701 is inverted: users won't need to migrate slots that specify their position with the in keyword, however any slot that doesn't specify their position will have to be set to a fixed, old, position to guarantee backwards compatibility.

2025-01-08 08:39 UTC, ironcev commented
> The lifecycle of migrations is (primarily) for existing codebases that are deployed behind proxies and need to maintain storage compatibility.

@IGI-111 Completely agree. I gave it a deeper thought and have a design that will cover both the rare case which is supported now and also contracts behind proxies. The two will play well together and also with the [SRC-14](https://docs.fuel.network/docs/sway-standards/src-14-simple-upgradeable-proxies/) (no suggestions to check `in` keywords for SRC-14 fields and fileds that have `in` keywords for compatibility, etc.).

I am moving the PR to draft until that is implemented.

2025-01-08 08:41 UTC, ironcev commented
> Given the code to track the manual effort duration for code changes and manual transformation suggestions, I take it (at least for now) the tool will work in a semi-automatic, as opposed to fully automatic?

@tritao It depends on the concrete breaking changes and also on the effort we want to put into writing migrations, compared to eventual manual effort. E.g., in the sample case of changing `ref mut` to `&mut` the migration can find and change usages etc. and make the step fully automatic.

But in a completely general case, I don't see a fully automatic migration as always possible, even theoretically. Also, the sensitivity of any migration always requires manual supervision. That's why I've opted for the proposed design in which the tool deliberately stops after a single feature is fully migrated and asks for a code review, even if all the migration steps were fully automated.

Having manual supervision and semi-automatic migrations also corresponds to my experience so far with code migrations. I see the goal of the tool in taking over the mundane and repetitive effort and pointing where to look, but programmers should still be aware of the changes and understand their impact.

2025-01-08 08:41 UTC, ironcev commented on forc-plugins/forc-migrate/src/cli/mod.rs
> +    Box::leak(
Yes it was new to me too :smile: And it sounded scary when I read it for the first time :smile:

2025-01-12 23:30 UTC, JoshuaBatty commented on forc-plugins/forc-migrate/src/cli/commands/run.rs
> +}
Is it worth make a temp backup of the files at the beginning so we only write to the original file if there were no errors?

```rust
pub(crate) fn output_changed_lexed_program(
    manifest_dir: &Path,
    modified_modules: &ModifiedModules,
    lexed_program: &LexedProgram,
) -> Result<()> {
    // Create backups before modifying files
  
    fn output_modules_rec(.....) -> Result<()> {
        .....
    }

    let result = output_modules_rec(manifest_dir, modified_modules, &lexed_program.root);
    
    // Clean up backups on success
    
    result
}
```

2025-01-17 02:26 UTC, ironcev commented on scripts/mdbook-forc-documenter/examples/forc_migrate.md
> +
My mother tongue doesn't have articles and knowing when **not** to use them is still one of the most difficult things in English for me. Portuguese has articles so I'll trust you on this one :smile:

2025-01-17 02:26 UTC, ironcev commented on forc-plugins/forc-migrate/src/lib.rs
> +/// The returned string is formatted to be used as an error message in the [anyhow::bail] macro.
Hmmm, in this case, I'll rather stick to the original version. The whole is formed _of_ some parts and _by_ someone or something, so my reasoning.

2025-01-17 02:27 UTC, ironcev commented on forc-plugins/forc-migrate/src/cli/shared.rs
> +pub(crate) struct Compile {
IMO it makes sense. E.g., the `forc doc` uses the same parameters, but those are currently mixed with other `doc` paramters in a single `Command`.

But I wouldn't do it as a part of this PR, which is already large in terms of changes and additions. There are other inconsistencies and overlaps accros the `forc-plugin` projects. IMO, documenting them and doing a low-prio step-by-step cleanup would be a way to go here.

2025-01-17 03:10 UTC, ironcev commented on forc-plugins/forc-migrate/src/cli/commands/run.rs
> +}
It could be done but, I think the effort wouldn't pay off. The reasons I see it as not necessary, or even counterproductive:
- `forc fmt` doesn't do it. Which makes sense. Devs know they are running a destructive operation without a "transactional guarantee".
- the `output_modules_rec` function can fail, disc issues aside, only if formatting fails, which means we have a bug and cannot migrate all the code because of it. In that case, it can even be desirable that at least the modules that have been successfully migrated stay modified/migrated.
- the migrations are deliberately designed to encourage devs to inspect their output. Means, they will always be diffed with the previous state of the repository. (Not migrating if the repo is dirty makes sense to be the default option. E.g., [ng update](https://angular.dev/cli/update) behaves so by default. I've just added detecting dirty repos to the list of potential improvements.) In case of a failure, a single `git restore .` will undo perfectly, if that is desired.


Please let me know if this reasoning makes sense, or you still see a strong reason for having transactional guarantee in this case. If so, I am anyhow for opening an issue to collect proposals for future improvements and then do the implementation as a part of it.

2025-01-17 03:22 UTC, ironcev commented
@IGI-111 @tritao @JoshuaBatty Thanks for reviewing the `forc migrate` tool. Can I ask you for a quick re-review of the latest changes? I need this PR merged to finalize the next one which brings additional migrations.

The latest changes address your remarks and also add some ~1000 LOC to the anyhow big PR. Still, it should be fairly easy to review.

The majority of the changes goes to infrastructure for matching and modifying trees. I hoped to get the first version of the `forc migrate` without necessarily developing such infrastructure. But it turned out that the LOC ratio between the code that does manual matching and tree modifications and the actual migration logic went to almost 3:1! This made the migrations error-prone and difficult to maintain. I expect in the future more improvements in this area as already discussed between @tritao and me (see: #6836). But for the time being, based on lot of concrete examples, I see the simple infrastructure provided in this PR as more than sufficient for writing readable and easy-to-write migrations.

2025-01-19 20:55 UTC, JoshuaBatty commented on forc-plugins/forc-migrate/src/cli/commands/run.rs
> +}
No dramas that makes sense. Thanks for the detailed reasoning!

2025-01-19 20:55 UTC, JoshuaBatty approved these changes

2025-01-20 12:14 UTC, merged