plugin: forc-call
FuelLabs/sway pull request #6791
Opened 2024-12-17 01:54 UTC by zees-dev

## Description
The following PR introduces a new forc plugin; `forc-call`.

This plugin allows users to call functions on deployed contracts using the `forc call` command.
This is ideal for quickly querying the state of a deployed contract.

In this first implementation; the contract ABI is required (as a path to a local JSON file or a URL to a remote JSON file).

This is inspired by the [`cast call`](https://book.getfoundry.sh/reference/cast/cast-call) tool; which is a popular tool for interacting with deployed contracts on Ethereum.
The implementation is based on the following Github issue: https://github.com/FuelLabs/sway/issues/6725

In the current implementation, you can query a contract state using the `forc call` command by providing the target contract ID, it's respective ABI file, and the function name (selector) and arguments.

<details>
  <summary>Forc Call CLI</summary>
  
  ```sh
  forc call --help
  ```

  ```
  Call a contract function

  Usage: forc call [OPTIONS] <CONTRACT_ID> <FUNCTION> [ARGS]...

  Arguments:
    <CONTRACT_ID>
            The contract ID to call

    <FUNCTION>
            The function signature to call. When ABI is provided, this should be a selector (e.g. "transfer") When no ABI is provided, this should be the full function signature (e.g. "transfer(address,u64)")

    [ARGS]...
            Arguments to pass into main function with forc run

  Options:
        --abi <ABI>
            Optional path or URI to a JSON ABI file

        --gas-price <PRICE>
            Gas price for the transaction

        --script-gas-limit <SCRIPT_GAS_LIMIT>
            Gas limit for the transaction

        --max-fee <MAX_FEE>
            Max fee for the transaction

        --node-url <NODE_URL>
            The URL of the Fuel node to which we're submitting the transaction. If unspecified, checks the manifest's `network` table, then falls back to `http://127.0.0.1:4000`
            
            You can also use `--target`, `--testnet`, or `--mainnet` to specify the Fuel node.
            
            [env: FUEL_NODE_URL=]

        --target <TARGET>
            Use preset configurations for deploying to a specific target.
            
            You can also use `--node-url`, `--testnet`, or `--mainnet` to specify the Fuel node.
            
            Possible values are: [local, testnet, mainnet]

        --testnet
            Use preset configuration for testnet.
            
            You can also use `--node-url`, `--target`, or `--mainnet` to specify the Fuel node.

        --mainnet
            Use preset configuration for mainnet.
            
            You can also use `--node-url`, `--target`, or `--testnet` to specify the Fuel node.

        --default-signer
            Sign the transaction with default signer that is pre-funded by fuel-core. Useful for testing against local node

        --signing-key <SIGNING_KEY>
            Set the key to be used for signing; required if default_signer is false

    -h, --help
            Print help (see a summary with '-h')

    -V, --version
            Print version
  ```
</details>

### Example usage

```sh
forc call 374aafbadfaf0c6522f1b4380c94706d78147a4f7c27edc2be4a9f1fa2e99759 --abi ./out/debug/counter-contract-abi.json "add" 1 2
```

- where `374aafbadfaf0c6522f1b4380c94706d78147a4f7c27edc2be4a9f1fa2e99759` is the contract ID
- where `./out/debug/counter-contract-abi.json` is the path to the ABI file
- where `add` is the function name (selector)
- where `1 2` are the arguments to the function

^ the sway code for the add function could be:

```sway
contract;

abi MyContract {
  fn add(a: u64, b: u64) -> u64;
}

impl MyContract for Contract {
  fn add(a: u64, b: u64) -> u64 {
    a + b
  }
}
```

## Implementation details

1. The provided ABI file downloaded (unless local path is provided)
2. The ABI is parsed into internal representation
3. The provided function selector e.g. `add` is matched with the extracted functions from the ABI
4. The provided arguments are parsed into the appropriate types which match the extracted function's inputs
5. The function selector and args are then converted into the `Token` enum, which is then ABI encoded as part of the `ContractCall` struct
6. The `ContractCall` struct is then used to make a request to the node to call the function
7. The response is then decoded into the appropriate type (based on matched function's output type)

^ In the implementation, we don't use the `abigen!` macro since this is a compile time parser of the ABI file; instead we make use of the lower level encoding and decoding primitives and functions from the [Rust SDK](https://github.com/FuelLabs/fuels-rs).

## Encoding cheat-sheet

A few of the common types are encoded as follows:

| Types                                      | Encoding Description                                                      | Example                                                                                          |
|--------------------------------------------|--------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------|
| bool, u8                                   | Encoded as a single byte. `bool`: 0x00 (false) or 0x01 (true); `u8` is the byte itself. | `bool(true) = 0x01`, `u8(42) = 0x2A`                                                     |
| u16                                        | 2-byte, big-endian                                                        | `u16(42) = 0x002A`                                                                             |
| u32                                        | 4-byte, big-endian                                                        | `u32(42) = 0x0000002A`                                                                        |
| u64                                        | 8-byte, big-endian                                                        | `u64(42) = 0x000000000000002A`                                                               |
| u128                                       | 16-byte, big-endian                                                       | `u128(42) = 0x0000000000000000000000000000002A`                                              |
| u256, b256                                 | 32-byte value. For u256: big-endian integer; For b256: raw 32 bytes       | `u256(42) = 32-bytes ending with ...0000002A`, `b256(...) = exactly the 32-byte array`       |
| Tuples, Arrays, Structs (Fixed-size)       | Concatenate the encodings of each element/field with no extra padding     | `(u8(1), bool(true)) = 0x01 0x01`; `[u16;2]: [42,100] = 0x002A0064`; `struct {u8,u8}: 0x0102` |
| Enums                                      | `u64` variant index + encoded variant data with no extra padding          | `MySumType::X(42): 0x0000000000000000 000000000000002A`                                       |
| Bytes, String, RawSlice, Vector (Dynamic)  | `u64` length prefix + raw data, no padding                                | `"abc" = length=3: 0x0000000000000003 0x61 0x62 0x63`                                         |

^ This is based on the docs here: https://docs.fuel.network/docs/specs/abi/argument-encoding

## Future improvements

1. Support for function signature based calls without ABI
2. Support for raw calldata input
3. Function selector completion - given ABI file

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necess [...]

2025-01-13 00:49 UTC, JoshuaBatty commented on forc-plugins/forc-client/src/op/call.rs
> +        let parsed_abi = UnifiedProgramABI::from_json_abi(&abi_str)?;
should we add validation to ensure ABI files are well-formed and compatible before progressing?

```rust
// Validate minimum required fields
if parsed_abi.functions.is_empty() {
    bail!("Invalid ABI: No functions found in ABI file");
}

...
```

2025-01-13 00:54 UTC, JoshuaBatty commented on forc-plugins/forc-client/src/cmd/call.rs
> +        [ Call a contract with function parameters => "forc call <CONTRACT_ID> <FUNCTION_SIGNATURE> <ARGS>" ]
i wonder if being a bit more explicit on what these calls look like might be easier for people to reference? I could go either but maybe the above could be 

```
[ Call a simple contract function => "forc call 0x123..abc add 1 2" ]
```

thoughts?

2025-01-13 00:58 UTC, JoshuaBatty commented on forc-plugins/forc-client/src/op/call.rs
> +                let tx_policies = gas.clone().map(Into::into).unwrap_or(TxPolicies::default());
```suggestion
                let tx_policies = gas.as_ref().map(Into::into).unwrap_or_else(TxPolicies::default);
```

Can probably remove the clone by using as_ref

2025-01-13 02:08 UTC, zees-dev commented on forc-plugins/forc-client/src/cmd/call.rs
> +        [ Call a contract with function parameters => "forc call <CONTRACT_ID> <FUNCTION_SIGNATURE> <ARGS>" ]
agreed; makes sense 👍

2025-01-13 02:45 UTC, zees-dev commented on forc-plugins/forc-client/src/op/call.rs
> +        let parsed_abi = UnifiedProgramABI::from_json_abi(&abi_str)?;
I was thinking we may want to support calling a contract without any functions - where you may want to only specify an amount.
In the case of solidity, this calls the default `fallback` or `receive` function - allowing the contract to receive funds.

I was unsure whether sway has an equivalent default function - or an approach where the contract can receive funds without calling an explicit function.

2025-01-13 03:53 UTC, zees-dev commented
Note: Currently CI fails since there is reliance on new release from [rust sdk](https://github.com/FuelLabs/fuels-rs) - which contains the relevant changes:
- https://github.com/FuelLabs/fuels-rs/pull/1553
- https://github.com/FuelLabs/fuels-rs/pull/1554

2025-01-14 07:08 UTC, Voxelot commented on forc-plugins/forc-client/src/op/call.rs
> +        let parsed_abi = UnifiedProgramABI::from_json_abi(&abi_str)?;
This is indeed possible, rather than using a `CALL` instruction, you can use a [`TR` or transfer instruction](https://docs.fuel.network/docs/specs/fuel-vm/instruction-set/#tr-transfer-coins-to-contract) to send funds into a contract.

https://docs.fuel.network/docs/nightly/fuels-ts/wallets/wallet-transferring/#transferring-assets-to-contracts

The sway also has a notion of default functions which are used by proxy contracts to pass-through calls and args to an implementation contract, but its not necessary to use this default function to receive funds.

2025-01-14 08:23 UTC, sdankel reviewed
Impressive work! It's still rough around the edges but I'm excited to use this.

2025-01-14 08:23 UTC, sdankel commented on forc-plugins/forc-client/src/cmd/call.rs
> +forc_util::cli_examples! {
For some reason these examples aren't showing up when I do `forc call --help`. Here's what I did to get it to build if you want the changes: https://github.com/FuelLabs/sway/pull/6831

Installed with `cargo install --path forc-plugins/forc-client`

2025-01-14 08:23 UTC, sdankel commented on forc-plugins/forc-client/src/op/call.rs
> +        bail!("Function must be a signature if no ABI is provided");
nit: It would be good to give an example here. 
```suggestion
        bail!("Function must be a signature if no ABI is provided, e.g. "transfer(address,u64)"
```

I wasn't able to get it to work without providing the ABI. These commands I tried all gave me panics:
- `forc call --testnet 0xd8b98e8ceebf08e2fbc4bf0599e8eae239608636b9aab76b5348c2174d197848 "initialize_counter(1)"`
- `forc call --testnet 0xd8b98e8ceebf08e2fbc4bf0599e8eae239608636b9aab76b5348c2174d197848 "initialize_counter(1, u64)"`
- `forc call --testnet 0xd8b98e8ceebf08e2fbc4bf0599e8eae239608636b9aab76b5348c2174d197848 "initialize_counter(value,u64) 1"`
- `forc call --testnet 0xd8b98e8ceebf08e2fbc4bf0599e8eae239608636b9aab76b5348c2174d197848 "initialize_counter(value,u64)" 1`
- `forc call --testnet 0xd8b98e8ceebf08e2fbc4bf0599e8eae239608636b9aab76b5348c2174d197848 "initialize_counter(value:u64)" 1`

This worked however: `forc call --testnet --abi examples/counter/out/debug/counter-abi.json 0xd8b98e8ceebf08e2fbc4bf0599e8eae239608636b9aab76b5348c2174d197848 "initialize_counter" 1 `

2025-01-14 08:23 UTC, sdankel commented on forc-plugins/forc-client/src/op/call.rs
> +            bail!("Function must be a selector");
It would be good to provide an example here:
```suggestion
            bail!("Function must be a selector, e.g \"transfer\"");
```

Even better would be if we could try to correctly print the function name that they entered.

2025-01-15 02:25 UTC, zees-dev commented on forc-plugins/forc-client/src/cmd/call.rs
> +forc_util::cli_examples! {
thanks for this!

2025-01-15 02:31 UTC, zees-dev commented on forc-plugins/forc-client/Cargo.toml
>  regex = "1.5.4"
addressed by you here: https://github.com/FuelLabs/sway/pull/6791#discussion_r1914400582 - thanks

2025-01-15 02:32 UTC, zees-dev commented on forc-plugins/forc-client/src/util/tx.rs
> +pub(crate) async fn select_local_wallet_account(
this is a big function; in fact i propose we incorporate this function in the function above - this way it can be re-used in both places.

2025-01-15 02:36 UTC, zees-dev commented on forc-plugins/forc-client/src/util/tx.rs
> +pub(crate) async fn select_local_wallet_account(
addressed: https://github.com/FuelLabs/sway/pull/6791/commits/014e9a7257af47c446aed9258b26ba5346e026e7

2025-01-15 02:37 UTC, zees-dev commented on forc-plugins/forc-client/src/util/node_url.rs
> +pub fn get_explorer_url(node_target: &NodeTarget) -> Option<String> {
https://github.com/FuelLabs/sway/pull/6791/commits/67e22a5d0198210f85dfb4d5d8f92146d5ae9912

2025-01-16 00:26 UTC, zees-dev commented on forc-plugins/forc-client/src/op/call.rs
> +use crate::{
addressed:
- https://github.com/FuelLabs/sway/pull/6791/commits/f8bbfb20cf53a8ade5906d54d2cd41980ed5cec8
- https://github.com/FuelLabs/sway/pull/6791/commits/9363181619c3e1914a0e97fbf44d6a904d5a6576

2025-01-16 02:06 UTC, zees-dev commented on forc-plugins/forc-client/src/op/call.rs
> +            bail!("Function must be a selector");
https://github.com/FuelLabs/sway/pull/6791/commits/931b825065a49a75bae67e56bbd61138e8bc992d

2025-01-17 00:46 UTC, sdankel commented on forc-plugins/forc-client/src/op/call.rs
> +        bail!("Function must be a signature if no ABI is provided");
Got it, we should just make sure the CLI isn't panicking in any scenario

2025-01-17 00:49 UTC, sdankel commented on forc-plugins/forc-client/src/cmd/call.rs
> +    pub abi: Option<Either<PathBuf, Url>>,
```suggestion
    /// Path or URI to a JSON ABI file.
    #[clap(long, value_parser = parse_abi_path)]
    pub abi: Either<PathBuf, Url>,
```

2025-02-04 00:37 UTC, zees-dev commented on forc-plugins/forc-client/src/cmd/call.rs
> +    /// When no ABI is provided, this should be the full function signature (e.g. "transfer(address,u64)")
https://github.com/FuelLabs/sway/pull/6791/commits/ce1d709506fc84ff9629803b7adfd32a673b86c5

2025-02-04 00:37 UTC, zees-dev commented on forc-plugins/forc-client/src/cmd/call.rs
> +    pub abi: Option<Either<PathBuf, Url>>,
https://github.com/FuelLabs/sway/pull/6791/commits/ce1d709506fc84ff9629803b7adfd32a673b86c5

2025-02-04 04:53 UTC, JoshuaBatty commented on forc-plugins/forc-client/src/cmd/call.rs
> +    // TODO: add support for function signatures - without ABI files
Have we got a github issue for this that we can mention here?

2025-02-04 05:20 UTC, zees-dev commented on forc-plugins/forc-client/src/cmd/call.rs
> +        // Check if function signature is a valid selector (alphanumeric and underscore support)
interesting; maybe ill just remove this requirement since we must also match the function in the abi too - which should enforce the correct naming conventions

2025-02-04 05:20 UTC, zees-dev commented on forc-plugins/forc-client/src/cmd/call.rs
> +    // TODO: add support for function signatures - without ABI files
No; i will add

2025-02-04 05:32 UTC, zees-dev commented on forc-plugins/forc-client/src/cmd/call.rs
> +        // Check if function signature is a valid selector (alphanumeric and underscore support)
https://github.com/FuelLabs/sway/pull/6791/commits/330596d0f2cd451c1410f3f35abe1f26c5404641

2025-02-04 05:32 UTC, zees-dev commented on forc-plugins/forc-client/src/cmd/call.rs
> +    // TODO: add support for function signatures - without ABI files
https://github.com/FuelLabs/sway/pull/6791/commits/e7e0c41d88d6e45698ce37e2b04cd74dc7673392

2025-02-04 11:33 UTC, alfiedotwtf commented
Apart from my comments, looks good. I'll wait for comments before hitting approve though

2025-02-05 02:29 UTC, JoshuaBatty commented on docs/book/src/forc/plugins/forc_client/forc_call.md
> +    Use preset configurations for deploying to a specific target.
what is forc call deploying?

2025-02-05 02:33 UTC, JoshuaBatty commented on forc-plugins/forc-client/src/op/call/missing_contracts.rs
> +pub async fn get_missing_contracts(
would be nice to add doc comments for all `pub` functions ...

2025-02-05 02:35 UTC, zees-dev commented on docs/book/src/forc/plugins/forc_client/forc_call.md
> +    Use preset configurations for deploying to a specific target.
nothing; it was using existing struct - which had original use in forc-deploy i believe.
Have updated the docs there and in the book:
https://github.com/FuelLabs/sway/pull/6791/commits/66451e764ad93b27fb6d712fbc625369e5ea74b8

2025-02-05 02:35 UTC, JoshuaBatty commented on forc-plugins/forc-client/src/op/call/mod.rs
> +    let abi_str = match abi {
would also be cool to try and fetch the verified ABI from the registry if only the contract id was given with no ABI file... obviously this isn't quite ready yet but would be a nice addition. Perhaps leaving a comment or linking to an issue to integrate this would be good.

2025-02-05 02:37 UTC, JoshuaBatty commented on forc-plugins/forc-client/src/op/call/parser.rs
> +        // enum GenericEnum<GenericStruct<u32>> {
do we need this commented section still?

2025-02-05 02:48 UTC, zees-dev commented on forc-plugins/forc-client/src/op/call/parser.rs
> +        // enum GenericEnum<GenericStruct<u32>> {
i think it's useful to keep it there for debugging purposes to know what we are dealing with; however can remove if we want

2025-02-05 02:50 UTC, JoshuaBatty commented on forc-plugins/forc-client/src/op/call/parser.rs
> +        // enum GenericEnum<GenericStruct<u32>> {
No worries, it's fine. If it's useful then leave it. Was just checking.

2025-02-05 02:52 UTC, zees-dev commented on forc-plugins/forc-client/src/op/call/missing_contracts.rs
> +pub async fn get_missing_contracts(
addressed:
- https://github.com/FuelLabs/sway/pull/6791/commits/870e4aa537f3d86e302667beab0b8294d3430a55
- https://github.com/FuelLabs/sway/pull/6791/commits/f99b8ab8dab24f44bf7dca761840004509dac86a

2025-02-05 02:58 UTC, zees-dev commented on forc-plugins/forc-client/src/op/call/mod.rs
> +    let abi_str = match abi {
https://github.com/FuelLabs/sway/pull/6791/commits/46e5007e434824916b964b26de81e6714e008047

2025-02-05 05:44 UTC, JoshuaBatty approved these changes
great work with this

2025-02-05 07:28 UTC, alfiedotwtf requested changes

2025-02-05 10:16 UTC, zees-dev commented on forc-plugins/forc-client/src/op/call/mod.rs
> +
this does fail

2025-02-05 10:17 UTC, zees-dev commented on forc-plugins/forc-client/src/op/call/parser.rs
> +                .expect("failed to select variant");
I dont think its required yet; maybe if people as for it.
I want to enable this once we get it right; was getting false positives in testing

2025-02-05 10:18 UTC, zees-dev commented on forc-plugins/forc-client/src/op/call/parser.rs
> +    }
Dont think so

2025-02-05 10:19 UTC, zees-dev commented on forc-plugins/forc-client/src/util/node_url.rs
>  /// Returns the URL to use for connecting to Fuel Core node.
Yea i think there was an issue with dependencies and due to this the migration was not straightforward; hence added a todo to address later.

2025-02-05 10:20 UTC, zees-dev commented on docs/book/src/forc/plugins/forc_client/forc_call.md
> +
not a bad idea

2025-02-05 10:24 UTC, zees-dev commented on docs/book/src/forc/plugins/forc_client/forc_call.md
> +
https://github.com/FuelLabs/sway/pull/6791/commits/0eb02256c50760a5e4eb345bc1bdd30198aeb470

2025-02-05 10:55 UTC, alfiedotwtf commented on forc-plugins/forc-client/src/op/call/mod.rs
> +
If it fails, shouldn't this unwrap the error then?

(just in case there's confusion, I'm talking about 493 `get_contract_call_cmd(id, &wallet, "test_array", vec!["[42, 42]"]);` which looking at it is returning 10 items?))

2025-02-05 11:20 UTC, zees-dev commented on forc-plugins/forc-client/src/op/call/mod.rs
> +
Im assuming you're talking about this test:
```rust
        // test_array - succeeds if length not matched!?
        let cmd = get_contract_call_cmd(id, &wallet, "test_array", vec!["[42, 42]"]);
        assert_eq!(
            call(cmd).await.unwrap(),
            "[42, 42, 0, 4718592, 65536, 65536, 0, 0, 0, 0]"
        );
```

Yes this should fail since the sway function is like so:
```sway
    fn test_array(a: [u64; 10]) -> [u64; 10] {
        a
    }
```

Ideally the function/compiler should throw an error if you pass in an incorrectly length slice (in the test we pass in a slice with 2 items; while the function requires an input slice of 10 items) - however this behaviour seems to be possible at sway level (regardless of this PR).

2025-02-05 11:29 UTC, alfiedotwtf commented on forc-plugins/forc-client/src/op/call/mod.rs
> +
Discussed further on slack.

2025-02-05 11:30 UTC, alfiedotwtf approved these changes

2025-02-05 22:51 UTC, sdankel commented on forc-plugins/forc-client/src/cmd/call.rs
> +    #[clap(long, default_value = "dry-run")]
Is it common in other tools to default to dryrun? A user gave feedback on sway playground asking to [default to live](https://github.com/FuelLabs/sway-playground/issues/110) since it currently defaults to dry-run.

2025-02-05 22:58 UTC, sdankel requested changes
I'm getting the following error:

```
$ forc call --testnet --abi examples/counter/out/debug/counter-abi.json 0xd8b98e8ceebf08e2fbc4bf0599e8eae239608636b9aab76b5348c2174d197848 initialize_counter 1

error: io: Response errors; Unknown field "indexation" on type "NodeInfo".
```

Does this command work for you? Could be I'm misreading the docs and the request is malformed. If that's the case we should have a more helpful error message.

2025-02-05 23:26 UTC, zees-dev commented on forc-plugins/forc-client/src/cmd/call.rs
> +    #[clap(long, default_value = "dry-run")]
Yeap this is common. 
Most people generally want to make queries - to query state. 
Querying state itself with live mode will cost user funds - we definitely don't want that.
Also if the user does not have funds, then they can't use live mode at all and hence can't perform any operation. 
Due to this dry-run, or simulation modes should be the default imo. 

Users who want to perform state changing operations that costs funds should be explicit (imo).

2025-02-06 05:44 UTC, sdankel approved these changes
🚀

2025-02-07 02:04 UTC, JoshuaBatty approved these changes

2025-02-07 02:30 UTC, merged