Rename forc doc `--manifest-path` to `--path`
FuelLabs/sway pull request #6797
Opened 2024-12-20 09:27 UTC by amiremohamadi

## Description
Closes https://github.com/FuelLabs/sway/issues/5789

## Checklist

- [x] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2024-12-23 23:15 UTC, zees-dev commented
There are still references to the `manifest-path` in the github workflow files; these will also need to be updated as part of the PR.

2024-12-30 21:34 UTC, ironcev requested changes
Thanks for the contribution :smile: :heart:

2024-12-30 21:34 UTC, ironcev commented on forc-plugins/forc-doc/src/cli.rs
> +    #[clap(long, alias = "manifest-path")]
To be aligned with the `forc build` and `forc fmt`, we should also have the short `-p` argument here: `#[clap(short, long)]`.

2024-12-30 21:34 UTC, ironcev commented on forc-plugins/forc-doc/src/cli.rs
>      /// Path to the Forc.toml file. By default, forc-doc searches for the Forc.toml
Let's also align the description with the `forc build` and `forc fmt`. Here I need to notice that those two tools already have a slightly different description. The proposal is to take the description from the `forc build` and use it also for `forc fmt` and `forc docs`. The proposal is to do this slight change in `forc fmt` also as a part of this PR.

2024-12-30 21:51 UTC, ironcev reviewed
@bitzoic We use to mark the breaking changes in the `forc` CLI with the `breaking_change` label and also to explain the change in the PR for devs who will eventually need to migrate their, e.g. CI scripts.

I would expect the same here. If devs, e.g., generate docs as a CI step this could break their workflows.

2025-01-01 15:40 UTC, ironcev approved these changes

2025-01-04 17:09 UTC, bitzoic approved these changes
Thank you!

2025-01-08 13:56 UTC, kayagokalp approved these changes

2025-01-08 22:18 UTC, JoshuaBatty approved these changes

2025-01-09 00:45 UTC, merged