Eliminate excessive error reporting.
FuelLabs/sway pull request #699
Opened 2022-01-24 23:58 UTC by emilyaherbert

Closes #60 . I tried to reproduce the provided issue as best as I could. If you can think of any more possible cases that you remember seeing / think may be an issue, let me know and I can add them to this PR.

2022-01-25 20:54 UTC, nfurfaro submitted a review, later dismissed
Looks good. Will be nice to see this merged!

2022-01-28 16:51 UTC, sezna requested changes
I'm not sure what this PR is trying to do. It looks like it is throwing away any "not found" errors that would come from the namespace.

Additionally, and this is my fault for not going through the issues, #60 is actually not really an issue any more. Back then we still had the brute force multi-pass compilation, and it would continually append the same error for each iteration. That's what caused #60.

2022-01-28 16:51 UTC, sezna commented on test/src/e2e_vm_tests/test_programs/excessive_error_reporting/Forc.toml
> +core = { git = "http://github.com/FuelLabs/sway-lib-core", version = "v0.0.1" }
```suggestion
```

2022-01-28 16:51 UTC, sezna commented on sway-core/src/semantic_analysis/ast_node/impl_trait.rs
> +        .ok(&mut prob_warnings, &mut prob_errors)
this just throws away the errors from `get_call_path`?

2022-02-01 00:33 UTC, emilyaherbert commented
I think there was a miscommunication about what the issue was about. I thought that #60 was asking for the two distinct errors to turn into one distinct error. i.e. to remove the "symbol not found" error because that information is basically repeated in the second error.

2022-02-01 00:33 UTC, closed without merging