Multi import statements with self syntax
FuelLabs/sway pull request #729
Opened 2022-02-01 00:46 UTC by mohammadfawaz

Closes https://github.com/FuelLabs/sway/issues/589
Supporting `self` and adding a new error message for when an alias is used with a `*` import.

I believe we now fully match the Rust syntax.

2022-02-02 00:51 UTC, otrho submitted a review, later dismissed
Looks good to me.  @sezna might want to review too before merge.

2022-02-02 21:34 UTC, sezna requested changes
seems reasonable to me; one tiny typo nit

2022-02-02 21:34 UTC, sezna commented on sway-core/src/semantic_analysis/namespace/arena.rs
> +        let last_item = new_path.pop().expect("Guranteed_by_grammar");
```suggestion
        let last_item = new_path.pop().expect("guaranteed by grammar");
```

2022-02-03 20:03 UTC, sezna approved these changes

2022-02-03 20:20 UTC, merged