fix: prevent panic when parsing empty string
FuelLabs/sway pull request #774
Opened 2022-02-11 21:53 UTC by alex-matthe

Close #748

2022-02-11 22:07 UTC, sezna commented on sway-core/src/lib.rs
> +    }
`ok()` constructs a compile result -- it is preferable to use that.
```suggestion

    ok(fuel_ast_op, warnings, errors)
```

2022-02-11 22:08 UTC, sezna requested changes
See comment

2022-02-12 02:48 UTC, sezna commented on sway-core/src/lib.rs
> +    }
Ah, I see. Could you add a method in `error.rs`, perhaps `pub fn new()`, that takes an option, warnings, and errors, and makes a compile result? That way we can use it in the future as well.

2022-02-15 00:45 UTC, sezna requested changes
Sorry for being unclear -- I meant as a _method_ of `CompileResult`. I think the name `new` is a bit too generic for a specific constructor.

To be more specific, [here](https://github.com/FuelLabs/sway/blob/master/sway-core/src/error.rs#L73), you'd want to add a block like this:
```rust
impl <T> CompileResult<T> {
    pub fn new( . . . ) etc.,
}
```

then you could use it like `CompileResult::new(...)`

2022-02-18 06:11 UTC, otrho commented
@alex-matthe @sezna This was getting a bit stale, so I've made the changes myself.  Ready to merge.

2022-02-18 14:07 UTC, sezna approved these changes

2022-02-18 14:07 UTC, merged