adds anyhow where result used to be
FuelLabs/sway pull request #860
Opened 2022-03-02 17:43 UTC by eureka-cpu

Intended to close #851

I've gone through and replaced any instance I could find of `Result<(), String>` with `anyhow`, along with error messages.

2022-03-02 22:49 UTC, JoshuaBatty requested changes
Nice, looks good thanks. Just left some comments to help you get the tests working again. 

There does still remain the question if we should be considering using `thiserror` instead of `anyhow` if we are exposing `forc` as a library. But this is still an upgrade from the current error handling and can be addressed in a separate PR if we decide to move to `thiserror`.

2022-03-02 22:49 UTC, JoshuaBatty commented on forc/src/utils/restricted_names.rs
> -        contains_invalid_char("test#proj", "package name"),
You should be able to get this to work again by just mapping the error returned by anyhow back to a string

`contains_invalid_char("test#proj", "package name").map_err(|e| e.to_string())`

2022-03-02 22:49 UTC, JoshuaBatty commented on forc/src/utils/restricted_names.rs
> -        contains_invalid_char("test proj", "package name"),
same here

`contains_invalid_char("", "package name").map_err(|e| e.to_string())`

2022-03-02 22:49 UTC, JoshuaBatty commented on forc/src/utils/restricted_names.rs
> -        contains_invalid_char("", "package name"),
and here 
`contains_invalid_char("", "package name").map_err(|e| e.to_string())`

2022-03-02 22:49 UTC, JoshuaBatty commented on forc/src/utils/restricted_names.rs
> -        contains_invalid_char("test_proj", "package name"),
`contains_invalid_char("test_proj", "package name").map_err(|e| e.to_string())`

2022-03-02 22:49 UTC, JoshuaBatty commented on forc/src/utils/restricted_names.rs
> +// unfortunately there's not a good way to test after converting to `anyhow`,
Can get rid of this whole commented block now

2022-03-02 23:11 UTC, mitchmindtree commented
Ahh was hoping to have this addressed after landing #825 but I should have mentioned so in the issue :smiling_face_with_tear: if this happens to land first I can rebase on top no worries :+1: 

---

I would like to see `thiserror` with more granular types eventually, but I think separating the parts of `forc` that we wish to expose as a library more clearly first might help to go about this, I'll open an issue with some thoughts on this. For now though I think `anyhow` and this PR makes a lot of sense!

2022-03-03 01:02 UTC, JoshuaBatty commented
I think it probably looked tidier the way you first had it, eg: 

```
assert_eq!(
    contains_invalid_char("test#proj", "package name").map_err(|e| e.to_string()),
    std::result::Result::Err(
        "invalid character `#` in package name: `test#proj`, \
            characters must be Unicode XID characters \
            (numbers, `-`, `_`, or most letters)"
            .into()
    )
);
```

2022-03-03 01:53 UTC, JoshuaBatty approved these changes
LGTM, thanks for addressing those changes.

2022-03-03 01:58 UTC, merged