Document Supertraits and `where` clauses
FuelLabs/sway pull request #969
Opened 2022-03-19 21:07 UTC by ControlCplusControlV

As always if my language doesn't match docs style or code examples aren't in depth enough lmk. The mention of the core library Ord isn't implemented yet but planning on getting to it, the examples don't focus on implementing other things but showing how you would, so if they need to be expanded into more real world examples I can do that

2022-03-19 22:03 UTC, mohammadfawaz requested changes
Thanks for doing this! When you make the requested changes, I will review again to make sure it's all coherent :)

2022-03-19 22:03 UTC, mohammadfawaz commented on docs/src/advanced/generic_types.md
> +Important background to know before diving into trait constraints is that the `where` clause can be used to specify needed traits of the generic argument. So when writing something like a Hashmap you
```suggestion
Important background to know before diving into trait constraints is that the `where` clause can be used to specify the required traits for the generic argument. So, when writing something like a `HashMap` you may
```

2022-03-19 22:03 UTC, mohammadfawaz commented on docs/src/advanced/generic_types.md
> +  where T: Hash
```suggestion
    where T: Hash
```

2022-03-19 22:03 UTC, mohammadfawaz commented on docs/src/advanced/generic_types.md
> +  // Code within here can then call functions assosiated with the Hash trait on Key
```suggestion
    // Code within here can then call functions associated with the Hash trait on Key
```

2022-03-19 22:03 UTC, mohammadfawaz commented on docs/src/advanced/generic_types.md
>  ## Trait Constraints
We should a note in italic at the end of this section that says that
"`where` clauses are still work-in-progress".

2022-03-19 22:41 UTC, ControlCplusControlV commented
Changes are added, really need to added code spell check to my nvim config

2022-03-20 03:09 UTC, mohammadfawaz requested changes
Two more minor things and you're good to go!

2022-03-20 03:09 UTC, mohammadfawaz commented on docs/src/advanced/generic_types.md
> +    // Code within here can then call functions associated with the Hash trait on Key
```suggestion
    // Code within here can then call methods associated with the Hash trait on Key
```

2022-03-20 03:09 UTC, mohammadfawaz commented on docs/src/advanced/generic_types.md
> +*`where` clauses are still work-in-progress, so some above statements may not be fully implemented*
Oh I think should actually go at the end of the "Traits Constraints" section instead.

2022-03-20 03:32 UTC, ControlCplusControlV commented
Changes committed  (Assuming I moved the warning to the right spot)

Should note this closes both #753 and #854

2022-03-20 03:51 UTC, mohammadfawaz approved these changes

2022-03-20 03:51 UTC, merged